{{- if .Values.networkPolicy.enabled }}
{{- $fullname := include "cartlabs.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-postgresql
  labels:
    {{- include "cartlabs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cartlabs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - { protocol: TCP, port: 5432 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-redis
  labels:
    {{- include "cartlabs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cartlabs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - { protocol: TCP, port: 6379 }
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullname }}-rabbitmq
  labels:
    {{- include "cartlabs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cartlabs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rabbitmq
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - { protocol: TCP, port: 5672 }
{{- end }}
