/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check process liveness */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check dependency readiness */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate as demo role */
        post: operations["demoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh session */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke refresh family */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List catalog categories */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search public products */
        get: operations["listCatalogProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/stores/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get verified public store profile */
        get: operations["getCatalogStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public product detail */
        get: operations["getCatalogProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get seller store */
        get: operations["getSellerStore"];
        put?: never;
        /** Create seller store */
        post: operations["createSellerStore"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update seller store */
        patch: operations["updateSellerStore"];
        trace?: never;
    };
    "/seller/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List seller products */
        get: operations["listSellerProducts"];
        put?: never;
        /** Create seller product */
        post: operations["createSellerProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get complete owned seller product */
        get: operations["getSellerProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update seller product */
        patch: operations["updateSellerProduct"];
        trace?: never;
    };
    "/seller/products/{productId}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create product variant */
        post: operations["createProductVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products/{productId}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add product image */
        post: operations["createProductImage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products/{productId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace owned product image without changing position */
        put: operations["replaceProductImage"];
        post?: never;
        /** Delete owned product image and compact remaining positions */
        delete: operations["deleteProductImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products/{productId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish complete draft or archived product immediately */
        post: operations["publishSellerProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/products/{productId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive published product */
        post: operations["archiveSellerProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/variants/{variantId}/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Adjust variant inventory */
        patch: operations["adjustVariantInventory"];
        trace?: never;
    };
    "/admin/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List stores for verification */
        get: operations["listAdminStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users newest first */
        get: operations["listAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{userId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend or reactivate user */
        patch: operations["updateAdminUserStatus"];
        trace?: never;
    };
    "/admin/stores/{storeId}/moderation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Verify or reject store */
        patch: operations["moderateStore"];
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List published and suspended products for enforcement */
        get: operations["listAdminProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{productId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspend or reinstate product listing */
        patch: operations["updateAdminProductStatus"];
        trace?: never;
    };
    "/cart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get buyer cart grouped by seller */
        get: operations["getCart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add or replace cart item quantity */
        put: operations["setCartItem"];
        post?: never;
        /** Remove cart item */
        delete: operations["removeCartItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reserve inventory and create seller orders
         * @description Reusing same Idempotency-Key returns original purchase without reserving twice.
         */
        post: operations["checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List buyer purchases */
        get: operations["listPurchases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchases/{purchaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get buyer purchase */
        get: operations["getPurchase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchases/{purchaseId}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete mock payment
         * @description Demo-only endpoint; provider sends signed webhook before response.
         */
        post: operations["completeDemoPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/purchases/{purchaseId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel purchase before fulfillment begins */
        post: operations["cancelPurchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders belonging to seller store */
        get: operations["listSellerOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Advance or cancel owned seller order */
        patch: operations["updateSellerOrderStatus"];
        trace?: never;
    };
    "/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Review item from delivered seller order */
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/products/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List verified delivered-purchase reviews */
        get: operations["listProductReviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get marketplace operating totals */
        get: operations["getAdminOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List newest fulfillment and trust audit events */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List durable user notifications */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive signed mock payment event */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            dependencies?: {
                [key: string]: string;
            };
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            requestId?: string;
        };
        /** @enum {string} */
        Role: "buyer" | "seller" | "admin";
        /** @enum {string} */
        UserStatus: "active" | "suspended";
        /** @enum {string} */
        ModerationStatus: "pending" | "approved" | "rejected";
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        DemoLoginRequest: {
            role: components["schemas"]["Role"];
        };
        Session: {
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["Role"];
        };
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            role: components["schemas"]["Role"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        UserStatusInput: {
            status: components["schemas"]["UserStatus"];
            reason: string;
        };
        StoreInput: {
            name: string;
            slug: string;
            description: string;
        };
        Store: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            sellerId: string;
            name: string;
            slug: string;
            description: string;
            status: components["schemas"]["ModerationStatus"];
            moderationNote: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        StoreProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            description: string;
            sellerDisplayName: string;
            /** Format: date-time */
            createdAt: string;
        };
        Category: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
        };
        ProductInput: {
            /** Format: uuid */
            categoryId: string;
            name: string;
            slug: string;
            description: string;
        };
        VariantInput: {
            sku: string;
            name: string;
            attributes: {
                [key: string]: string;
            };
            /** Format: int64 */
            priceMinor: number;
            /** @enum {string} */
            currency: "IDR";
            stock: number;
        };
        Variant: {
            /** Format: uuid */
            id: string;
            sku: string;
            name: string;
            attributes: {
                [key: string]: string;
            };
            /** Format: int64 */
            priceMinor: number;
            /** @enum {string} */
            currency: "IDR";
            stock: number;
            active: boolean;
        };
        ImageInput: {
            /** Format: uri-reference */
            url: string;
            altText: string;
            position?: number;
        };
        ImageReplacementInput: {
            /** Format: uri-reference */
            url: string;
            altText: string;
        };
        ProductImage: {
            /** Format: uuid */
            id: string;
            /** Format: uri-reference */
            url: string;
            altText: string;
            position: number;
        };
        ProductSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            storeName: string;
            storeSlug: string;
            category: components["schemas"]["Category"];
            /** Format: int64 */
            minPriceMinor: number;
            currency: string;
            inStock: boolean;
            imageUrl: string;
        };
        ProductDetail: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            storeId: string;
            storeName?: string;
            storeSlug: string;
            category: components["schemas"]["Category"];
            name: string;
            slug: string;
            description: string;
            /** @enum {string} */
            status: "draft" | "published" | "archived" | "suspended";
            variants: components["schemas"]["Variant"][];
            images: components["schemas"]["ProductImage"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminProduct: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            storeId: string;
            storeName?: string;
            storeSlug: string;
            category: components["schemas"]["Category"];
            name: string;
            slug: string;
            description: string;
            /** @enum {string} */
            status: "published" | "suspended";
            variants: components["schemas"]["Variant"][];
            images: components["schemas"]["ProductImage"][];
            enforcementReason: string;
            /** Format: date-time */
            enforcedAt: string | null;
            enforcedBy: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProductPage: {
            items: components["schemas"]["ProductSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        InventoryAdjustment: {
            delta: number;
            reason: string;
        };
        ModerationInput: {
            /** @enum {string} */
            status: "approved" | "rejected";
            note: string;
        };
        ProductStatusInput: {
            /** @enum {string} */
            status: "suspended" | "published";
            reason: string;
        };
        CartItemInput: {
            quantity: number;
        };
        CartItem: {
            /** Format: uuid */
            variantId: string;
            /** Format: uuid */
            productId: string;
            productName: string;
            productSlug: string;
            variantName: string;
            sku: string;
            /** Format: uri-reference */
            imageUrl: string;
            quantity: number;
            availableStock: number;
            /** Format: int64 */
            unitPriceMinor: number;
            /** Format: int64 */
            lineTotalMinor: number;
            /** @enum {string} */
            currency: "IDR";
        };
        CartStore: {
            /** Format: uuid */
            storeId: string;
            storeName: string;
            items: components["schemas"]["CartItem"][];
            /** Format: int64 */
            subtotalMinor: number;
        };
        Cart: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            currency: "IDR";
            stores: components["schemas"]["CartStore"][];
            /** Format: int64 */
            subtotalMinor: number;
            totalQuantity: number;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        PurchaseStatus: "pending_payment" | "paid" | "payment_failed" | "expired" | "cancelled";
        /** @enum {string} */
        PaymentStatus: "pending" | "succeeded" | "failed" | "expired" | "cancelled";
        /** @enum {string} */
        SellerOrderStatus: "pending_payment" | "paid" | "processing" | "shipped" | "delivered" | "cancelled";
        PurchaseItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            productId: string;
            /** Format: uuid */
            variantId: string;
            productName: string;
            variantName: string;
            sku: string;
            /** Format: uri-reference */
            imageUrl: string;
            quantity: number;
            /** Format: int64 */
            unitPriceMinor: number;
            /** Format: int64 */
            lineTotalMinor: number;
            /** @enum {string} */
            currency: "IDR";
        };
        SellerOrder: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            purchaseId: string;
            reference: string;
            /** Format: uuid */
            storeId: string;
            storeName: string;
            status: components["schemas"]["SellerOrderStatus"];
            /** @enum {string} */
            currency: "IDR";
            /** Format: int64 */
            subtotalMinor: number;
            items: components["schemas"]["PurchaseItem"][];
            /** Format: date-time */
            processingAt?: string;
            /** Format: date-time */
            shippedAt?: string;
            /** Format: date-time */
            deliveredAt?: string;
            /** Format: date-time */
            cancelledAt?: string;
            cancellationReason: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Purchase: {
            /** Format: uuid */
            id: string;
            reference: string;
            /** Format: uuid */
            buyerId: string;
            status: components["schemas"]["PurchaseStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            paymentIntentId: string;
            /** @enum {string} */
            currency: "IDR";
            /** Format: int64 */
            subtotalMinor: number;
            /** Format: int64 */
            totalMinor: number;
            /** Format: date-time */
            reservationExpiresAt: string;
            sellerOrders: components["schemas"]["SellerOrder"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PaymentCompletionInput: {
            /** @enum {string} */
            outcome: "succeeded" | "failed";
        };
        CancellationInput: {
            reason: string;
        };
        FulfillmentInput: {
            /** @enum {string} */
            status: "processing" | "shipped" | "delivered" | "cancelled";
            /** @default  */
            reason: string;
        };
        ReviewInput: {
            /** Format: uuid */
            purchaseItemId: string;
            rating: number;
            title: string;
            body: string;
        };
        Review: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            buyerId: string;
            buyerName: string;
            /** Format: uuid */
            purchaseItemId: string;
            /** Format: uuid */
            productId: string;
            rating: number;
            title: string;
            body: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ReviewSummary: {
            /** Format: double */
            average: number;
            count: number;
            items: components["schemas"]["Review"][];
        };
        AdminOverview: {
            /** Format: int64 */
            users: number;
            /** Format: int64 */
            approvedStores: number;
            /** Format: int64 */
            publishedProducts: number;
            /** Format: int64 */
            purchases: number;
            /** Format: int64 */
            activeSellerOrders: number;
            /** Format: int64 */
            deliveredOrders: number;
            /** Format: int64 */
            grossMerchandiseMinor: number;
            /** @enum {string} */
            currency: "IDR";
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorId?: string;
            actorName?: string;
            /** @enum {string} */
            actorRole: "buyer" | "seller" | "admin" | "system";
            action: string;
            resourceType: string;
            /** Format: uuid */
            resourceId: string;
            data: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        PaymentWebhookEvent: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "payment.succeeded" | "payment.failed";
            /** Format: date-time */
            createdAt: string;
            data: {
                /** Format: uuid */
                intentId: string;
                reference: string;
                /** Format: int64 */
                amountMinor: number;
                /** @enum {string} */
                currency: "IDR";
            };
        };
        Notification: {
            /** Format: uuid */
            id: string;
            kind: string;
            title: string;
            body: string;
            /** Format: date-time */
            readAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        ServiceUnavailableProblem: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Invalid request */
        Problem400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invalid credentials or session */
        Problem401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Insufficient permission */
        Problem403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Resource not found */
        Problem404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description State conflict */
        Problem409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication attempts exceeded */
        Problem429: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Dependency unavailable */
        Problem503: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Health"];
            };
        };
        /** @description Authentication limiter unavailable */
        Problem503JSON: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ProductId: string;
        ImageId: string;
        VariantId: string;
        StoreId: string;
        UserId: string;
        PurchaseId: string;
        OrderId: string;
        IdempotencyKey: string;
        ProductSlug: string;
        StoreSlug: string;
        Search: string;
        CategoryFilter: string;
        StoreFilter: string;
        MinPrice: number;
        MaxPrice: number;
        InStock: boolean;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; refresh cookie set */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailableProblem"];
        };
    };
    demoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated as deterministic demo account */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailableProblem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session rotated */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Refresh family revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Category"][];
                    };
                };
            };
        };
    };
    listCatalogProducts: {
        parameters: {
            query?: {
                q?: components["parameters"]["Search"];
                category?: components["parameters"]["CategoryFilter"];
                store?: components["parameters"]["StoreFilter"];
                minPrice?: components["parameters"]["MinPrice"];
                maxPrice?: components["parameters"]["MaxPrice"];
                inStock?: components["parameters"]["InStock"];
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published products from verified stores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCatalogStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["StoreSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approved public store profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "01989f00-0000-7000-8000-000000000010",
                     *       "name": "Nusantara Crafts",
                     *       "slug": "nusantara-crafts",
                     *       "description": "Handmade goods from local makers.",
                     *       "sellerDisplayName": "Sari",
                     *       "createdAt": "2026-08-12T10:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["StoreProfile"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCatalogProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ProductSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published product detail from verified store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSellerStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seller store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createSellerStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreInput"];
            };
        };
        responses: {
            /** @description Store submitted for verification */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    updateSellerStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreInput"];
            };
        };
        responses: {
            /** @description Updated store; material changes return to pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listSellerProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products owned by seller store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProductDetail"][];
                    };
                };
            };
        };
    };
    createSellerProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Draft product */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
        };
    };
    getSellerProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complete owned product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateSellerProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductInput"];
            };
        };
        responses: {
            /** @description Updated draft product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createProductVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VariantInput"];
            };
        };
        responses: {
            /** @description Product variant */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageInput"];
            };
        };
        responses: {
            /** @description Product image */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    replaceProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
                imageId: components["parameters"]["ImageId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageReplacementInput"];
            };
        };
        responses: {
            /** @description Replaced product image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductImage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProductImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
                imageId: components["parameters"]["ImageId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product image deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    publishSellerProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    archiveSellerProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived product */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    adjustVariantInventory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: components["parameters"]["VariantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InventoryAdjustment"];
            };
        };
        responses: {
            /** @description Updated variant */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Variant"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    listAdminStores: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stores awaiting or having verification */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Store"][];
                    };
                };
            };
        };
    };
    listAdminUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Admin-safe user list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminUser"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateAdminUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "suspended",
                 *       "reason": "Repeated marketplace policy violations"
                 *     }
                 */
                "application/json": components["schemas"]["UserStatusInput"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    moderateStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: components["parameters"]["StoreId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationInput"];
            };
        };
        responses: {
            /** @description Verified or rejected store */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Store"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listAdminProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enforceable listings with latest suspension context */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AdminProduct"][];
                    };
                };
            };
        };
    };
    updateAdminProductStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                productId: components["parameters"]["ProductId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductStatusInput"];
            };
        };
        responses: {
            /** @description Updated enforceable listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProduct"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current cart with live price and stock */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    setCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: components["parameters"]["VariantId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CartItemInput"];
            };
        };
        responses: {
            /** @description Updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeCartItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                variantId: components["parameters"]["VariantId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated cart */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    checkout: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase and payment intent created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailableProblem"];
        };
    };
    listPurchases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Buyer purchases newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Purchase"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    getPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchaseId: components["parameters"]["PurchaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Purchase with seller orders and immutable item snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    completeDemoPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchaseId: components["parameters"]["PurchaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentCompletionInput"];
            };
        };
        responses: {
            /** @description Purchase after webhook transition */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            503: components["responses"]["ServiceUnavailableProblem"];
        };
    };
    cancelPurchase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purchaseId: components["parameters"]["PurchaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancellationInput"];
            };
        };
        responses: {
            /** @description Cancelled purchase with restored inventory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Purchase"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSellerOrders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Seller order snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["SellerOrder"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    updateSellerOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                orderId: components["parameters"]["OrderId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FulfillmentInput"];
            };
        };
        responses: {
            /** @description Updated seller order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SellerOrder"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewInput"];
            };
        };
        responses: {
            /** @description Verified-purchase review */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            400: components["responses"]["BadRequest"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    listProductReviews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["ProductSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Review summary and newest reviews */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getAdminOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marketplace overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminOverview"];
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit events newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Notifications newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Notification"][];
                    };
                };
            };
            403: components["responses"]["Forbidden"];
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-Cartlabs-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentWebhookEvent"];
            };
        };
        responses: {
            /** @description Event accepted or already processed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
