// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminOverviewCurrency.
const (
	AdminOverviewCurrencyIDR AdminOverviewCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the AdminOverviewCurrency enum.
func (e AdminOverviewCurrency) Valid() bool {
	switch e {
	case AdminOverviewCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for AdminProductStatus.
const (
	AdminProductStatusPublished AdminProductStatus = "published"
	AdminProductStatusSuspended AdminProductStatus = "suspended"
)

// Valid indicates whether the value is a known member of the AdminProductStatus enum.
func (e AdminProductStatus) Valid() bool {
	switch e {
	case AdminProductStatusPublished:
		return true
	case AdminProductStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventActorRole.
const (
	AuditEventActorRoleAdmin  AuditEventActorRole = "admin"
	AuditEventActorRoleBuyer  AuditEventActorRole = "buyer"
	AuditEventActorRoleSeller AuditEventActorRole = "seller"
	AuditEventActorRoleSystem AuditEventActorRole = "system"
)

// Valid indicates whether the value is a known member of the AuditEventActorRole enum.
func (e AuditEventActorRole) Valid() bool {
	switch e {
	case AuditEventActorRoleAdmin:
		return true
	case AuditEventActorRoleBuyer:
		return true
	case AuditEventActorRoleSeller:
		return true
	case AuditEventActorRoleSystem:
		return true
	default:
		return false
	}
}

// Defines values for CartCurrency.
const (
	CartCurrencyIDR CartCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartCurrency enum.
func (e CartCurrency) Valid() bool {
	switch e {
	case CartCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for CartItemCurrency.
const (
	CartItemCurrencyIDR CartItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartItemCurrency enum.
func (e CartItemCurrency) Valid() bool {
	switch e {
	case CartItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for FulfillmentInputStatus.
const (
	FulfillmentInputStatusCancelled  FulfillmentInputStatus = "cancelled"
	FulfillmentInputStatusDelivered  FulfillmentInputStatus = "delivered"
	FulfillmentInputStatusProcessing FulfillmentInputStatus = "processing"
	FulfillmentInputStatusShipped    FulfillmentInputStatus = "shipped"
)

// Valid indicates whether the value is a known member of the FulfillmentInputStatus enum.
func (e FulfillmentInputStatus) Valid() bool {
	switch e {
	case FulfillmentInputStatusCancelled:
		return true
	case FulfillmentInputStatusDelivered:
		return true
	case FulfillmentInputStatusProcessing:
		return true
	case FulfillmentInputStatusShipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ModerationInputStatus.
const (
	ModerationInputStatusApproved ModerationInputStatus = "approved"
	ModerationInputStatusRejected ModerationInputStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationInputStatus enum.
func (e ModerationInputStatus) Valid() bool {
	switch e {
	case ModerationInputStatusApproved:
		return true
	case ModerationInputStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ModerationStatus.
const (
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusRejected ModerationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationStatus enum.
func (e ModerationStatus) Valid() bool {
	switch e {
	case ModerationStatusApproved:
		return true
	case ModerationStatusPending:
		return true
	case ModerationStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PaymentCompletionInputOutcome.
const (
	PaymentCompletionInputOutcomeFailed    PaymentCompletionInputOutcome = "failed"
	PaymentCompletionInputOutcomeSucceeded PaymentCompletionInputOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentCompletionInputOutcome enum.
func (e PaymentCompletionInputOutcome) Valid() bool {
	switch e {
	case PaymentCompletionInputOutcomeFailed:
		return true
	case PaymentCompletionInputOutcomeSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatus.
const (
	PaymentStatusCancelled PaymentStatus = "cancelled"
	PaymentStatusExpired   PaymentStatus = "expired"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusSucceeded PaymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusCancelled:
		return true
	case PaymentStatusExpired:
		return true
	case PaymentStatusFailed:
		return true
	case PaymentStatusPending:
		return true
	case PaymentStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventDataCurrency.
const (
	PaymentWebhookEventDataCurrencyIDR PaymentWebhookEventDataCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventDataCurrency enum.
func (e PaymentWebhookEventDataCurrency) Valid() bool {
	switch e {
	case PaymentWebhookEventDataCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventType.
const (
	PaymentWebhookEventTypePaymentFailed    PaymentWebhookEventType = "payment.failed"
	PaymentWebhookEventTypePaymentSucceeded PaymentWebhookEventType = "payment.succeeded"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventType enum.
func (e PaymentWebhookEventType) Valid() bool {
	switch e {
	case PaymentWebhookEventTypePaymentFailed:
		return true
	case PaymentWebhookEventTypePaymentSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ProductDetailStatus.
const (
	ProductDetailStatusArchived  ProductDetailStatus = "archived"
	ProductDetailStatusDraft     ProductDetailStatus = "draft"
	ProductDetailStatusPublished ProductDetailStatus = "published"
	ProductDetailStatusSuspended ProductDetailStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProductDetailStatus enum.
func (e ProductDetailStatus) Valid() bool {
	switch e {
	case ProductDetailStatusArchived:
		return true
	case ProductDetailStatusDraft:
		return true
	case ProductDetailStatusPublished:
		return true
	case ProductDetailStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ProductStatusInputStatus.
const (
	ProductStatusInputStatusPublished ProductStatusInputStatus = "published"
	ProductStatusInputStatusSuspended ProductStatusInputStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProductStatusInputStatus enum.
func (e ProductStatusInputStatus) Valid() bool {
	switch e {
	case ProductStatusInputStatusPublished:
		return true
	case ProductStatusInputStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseCurrency.
const (
	PurchaseCurrencyIDR PurchaseCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseCurrency enum.
func (e PurchaseCurrency) Valid() bool {
	switch e {
	case PurchaseCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseItemCurrency.
const (
	PurchaseItemCurrencyIDR PurchaseItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseItemCurrency enum.
func (e PurchaseItemCurrency) Valid() bool {
	switch e {
	case PurchaseItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseStatus.
const (
	PurchaseStatusCancelled      PurchaseStatus = "cancelled"
	PurchaseStatusExpired        PurchaseStatus = "expired"
	PurchaseStatusPaid           PurchaseStatus = "paid"
	PurchaseStatusPaymentFailed  PurchaseStatus = "payment_failed"
	PurchaseStatusPendingPayment PurchaseStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the PurchaseStatus enum.
func (e PurchaseStatus) Valid() bool {
	switch e {
	case PurchaseStatusCancelled:
		return true
	case PurchaseStatusExpired:
		return true
	case PurchaseStatusPaid:
		return true
	case PurchaseStatusPaymentFailed:
		return true
	case PurchaseStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleBuyer  Role = "buyer"
	RoleSeller Role = "seller"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleBuyer:
		return true
	case RoleSeller:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderCurrency.
const (
	SellerOrderCurrencyIDR SellerOrderCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the SellerOrderCurrency enum.
func (e SellerOrderCurrency) Valid() bool {
	switch e {
	case SellerOrderCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderStatus.
const (
	SellerOrderStatusCancelled      SellerOrderStatus = "cancelled"
	SellerOrderStatusDelivered      SellerOrderStatus = "delivered"
	SellerOrderStatusPaid           SellerOrderStatus = "paid"
	SellerOrderStatusPendingPayment SellerOrderStatus = "pending_payment"
	SellerOrderStatusProcessing     SellerOrderStatus = "processing"
	SellerOrderStatusShipped        SellerOrderStatus = "shipped"
)

// Valid indicates whether the value is a known member of the SellerOrderStatus enum.
func (e SellerOrderStatus) Valid() bool {
	switch e {
	case SellerOrderStatusCancelled:
		return true
	case SellerOrderStatusDelivered:
		return true
	case SellerOrderStatusPaid:
		return true
	case SellerOrderStatusPendingPayment:
		return true
	case SellerOrderStatusProcessing:
		return true
	case SellerOrderStatusShipped:
		return true
	default:
		return false
	}
}

// Defines values for SessionTokenType.
const (
	Bearer SessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionTokenType enum.
func (e SessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for VariantCurrency.
const (
	VariantCurrencyIDR VariantCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantCurrency enum.
func (e VariantCurrency) Valid() bool {
	switch e {
	case VariantCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for VariantInputCurrency.
const (
	VariantInputCurrencyIDR VariantInputCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantInputCurrency enum.
func (e VariantInputCurrency) Valid() bool {
	switch e {
	case VariantInputCurrencyIDR:
		return true
	default:
		return false
	}
}

// AdminOverview defines model for AdminOverview.
type AdminOverview struct {
	ActiveSellerOrders    int64                 `json:"activeSellerOrders"`
	ApprovedStores        int64                 `json:"approvedStores"`
	Currency              AdminOverviewCurrency `json:"currency"`
	DeliveredOrders       int64                 `json:"deliveredOrders"`
	GrossMerchandiseMinor int64                 `json:"grossMerchandiseMinor"`
	PublishedProducts     int64                 `json:"publishedProducts"`
	Purchases             int64                 `json:"purchases"`
	Users                 int64                 `json:"users"`
}

// AdminOverviewCurrency defines model for AdminOverview.Currency.
type AdminOverviewCurrency string

// AdminProduct defines model for AdminProduct.
type AdminProduct struct {
	Category          Category           `json:"category"`
	CreatedAt         time.Time          `json:"createdAt"`
	Description       string             `json:"description"`
	EnforcedAt        *time.Time         `json:"enforcedAt"`
	EnforcedBy        *string            `json:"enforcedBy"`
	EnforcementReason string             `json:"enforcementReason"`
	Id                openapi_types.UUID `json:"id"`
	Images            []ProductImage     `json:"images"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Status            AdminProductStatus `json:"status"`
	StoreId           openapi_types.UUID `json:"storeId"`
	StoreName         *string            `json:"storeName,omitempty"`
	StoreSlug         string             `json:"storeSlug"`
	UpdatedAt         time.Time          `json:"updatedAt"`
	Variants          []Variant          `json:"variants"`
}

// AdminProductStatus defines model for AdminProduct.Status.
type AdminProductStatus string

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
	Status      UserStatus          `json:"status"`
	UpdatedAt   time.Time           `json:"updatedAt"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action       string                 `json:"action"`
	ActorId      *openapi_types.UUID    `json:"actorId,omitempty"`
	ActorName    *string                `json:"actorName,omitempty"`
	ActorRole    AuditEventActorRole    `json:"actorRole"`
	CreatedAt    time.Time              `json:"createdAt"`
	Data         map[string]interface{} `json:"data"`
	Id           openapi_types.UUID     `json:"id"`
	ResourceId   openapi_types.UUID     `json:"resourceId"`
	ResourceType string                 `json:"resourceType"`
}

// AuditEventActorRole defines model for AuditEvent.ActorRole.
type AuditEventActorRole string

// CancellationInput defines model for CancellationInput.
type CancellationInput struct {
	Reason string `json:"reason"`
}

// Cart defines model for Cart.
type Cart struct {
	Currency      CartCurrency       `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	Stores        []CartStore        `json:"stores"`
	SubtotalMinor int64              `json:"subtotalMinor"`
	TotalQuantity int                `json:"totalQuantity"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// CartCurrency defines model for Cart.Currency.
type CartCurrency string

// CartItem defines model for CartItem.
type CartItem struct {
	AvailableStock int                `json:"availableStock"`
	Currency       CartItemCurrency   `json:"currency"`
	ImageUrl       string             `json:"imageUrl"`
	LineTotalMinor int64              `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID `json:"productId"`
	ProductName    string             `json:"productName"`
	ProductSlug    string             `json:"productSlug"`
	Quantity       int                `json:"quantity"`
	Sku            string             `json:"sku"`
	UnitPriceMinor int64              `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID `json:"variantId"`
	VariantName    string             `json:"variantName"`
}

// CartItemCurrency defines model for CartItem.Currency.
type CartItemCurrency string

// CartItemInput defines model for CartItemInput.
type CartItemInput struct {
	Quantity int `json:"quantity"`
}

// CartStore defines model for CartStore.
type CartStore struct {
	Items         []CartItem         `json:"items"`
	StoreId       openapi_types.UUID `json:"storeId"`
	StoreName     string             `json:"storeName"`
	SubtotalMinor int64              `json:"subtotalMinor"`
}

// Category defines model for Category.
type Category struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// DemoLoginRequest defines model for DemoLoginRequest.
type DemoLoginRequest struct {
	Role Role `json:"role"`
}

// FulfillmentInput defines model for FulfillmentInput.
type FulfillmentInput struct {
	Reason *string                `json:"reason,omitempty"`
	Status FulfillmentInputStatus `json:"status"`
}

// FulfillmentInputStatus defines model for FulfillmentInput.Status.
type FulfillmentInputStatus string

// Health defines model for Health.
type Health struct {
	Dependencies *map[string]string `json:"dependencies,omitempty"`
	Status       HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImageInput defines model for ImageInput.
type ImageInput struct {
	AltText  string `json:"altText"`
	Position *int   `json:"position,omitempty"`
	Url      string `json:"url"`
}

// ImageReplacementInput defines model for ImageReplacementInput.
type ImageReplacementInput struct {
	AltText string `json:"altText"`
	Url     string `json:"url"`
}

// InventoryAdjustment defines model for InventoryAdjustment.
type InventoryAdjustment struct {
	Delta  int    `json:"delta"`
	Reason string `json:"reason"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ModerationInput defines model for ModerationInput.
type ModerationInput struct {
	Note   string                `json:"note"`
	Status ModerationInputStatus `json:"status"`
}

// ModerationInputStatus defines model for ModerationInput.Status.
type ModerationInputStatus string

// ModerationStatus defines model for ModerationStatus.
type ModerationStatus string

// Notification defines model for Notification.
type Notification struct {
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"createdAt"`
	Href      string             `json:"href"`
	Id        openapi_types.UUID `json:"id"`
	Kind      string             `json:"kind"`
	ReadAt    *time.Time         `json:"readAt,omitempty"`
	Title     string             `json:"title"`
}

// PaymentCompletionInput defines model for PaymentCompletionInput.
type PaymentCompletionInput struct {
	Outcome PaymentCompletionInputOutcome `json:"outcome"`
}

// PaymentCompletionInputOutcome defines model for PaymentCompletionInput.Outcome.
type PaymentCompletionInputOutcome string

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PaymentWebhookEvent defines model for PaymentWebhookEvent.
type PaymentWebhookEvent struct {
	CreatedAt time.Time `json:"createdAt"`
	Data      struct {
		AmountMinor int64                           `json:"amountMinor"`
		Currency    PaymentWebhookEventDataCurrency `json:"currency"`
		IntentId    openapi_types.UUID              `json:"intentId"`
		Reference   string                          `json:"reference"`
	} `json:"data"`
	Id   openapi_types.UUID      `json:"id"`
	Type PaymentWebhookEventType `json:"type"`
}

// PaymentWebhookEventDataCurrency defines model for PaymentWebhookEvent.Data.Currency.
type PaymentWebhookEventDataCurrency string

// PaymentWebhookEventType defines model for PaymentWebhookEvent.Type.
type PaymentWebhookEventType string

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// ProductDetail defines model for ProductDetail.
type ProductDetail struct {
	Category    Category            `json:"category"`
	CreatedAt   time.Time           `json:"createdAt"`
	Description string              `json:"description"`
	Id          openapi_types.UUID  `json:"id"`
	Images      []ProductImage      `json:"images"`
	Name        string              `json:"name"`
	Slug        string              `json:"slug"`
	Status      ProductDetailStatus `json:"status"`
	StoreId     openapi_types.UUID  `json:"storeId"`
	StoreName   *string             `json:"storeName,omitempty"`
	StoreSlug   string              `json:"storeSlug"`
	UpdatedAt   time.Time           `json:"updatedAt"`
	Variants    []Variant           `json:"variants"`
}

// ProductDetailStatus defines model for ProductDetail.Status.
type ProductDetailStatus string

// ProductImage defines model for ProductImage.
type ProductImage struct {
	AltText  string             `json:"altText"`
	Id       openapi_types.UUID `json:"id"`
	Position int                `json:"position"`
	Url      string             `json:"url"`
}

// ProductInput defines model for ProductInput.
type ProductInput struct {
	CategoryId  openapi_types.UUID `json:"categoryId"`
	Description string             `json:"description"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
}

// ProductPage defines model for ProductPage.
type ProductPage struct {
	Items    []ProductSummary `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// ProductStatusInput defines model for ProductStatusInput.
type ProductStatusInput struct {
	Reason string                   `json:"reason"`
	Status ProductStatusInputStatus `json:"status"`
}

// ProductStatusInputStatus defines model for ProductStatusInput.Status.
type ProductStatusInputStatus string

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	Category      Category           `json:"category"`
	Currency      string             `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	ImageUrl      string             `json:"imageUrl"`
	InStock       bool               `json:"inStock"`
	MinPriceMinor int64              `json:"minPriceMinor"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	StoreName     string             `json:"storeName"`
	StoreSlug     string             `json:"storeSlug"`
}

// Purchase defines model for Purchase.
type Purchase struct {
	BuyerId              openapi_types.UUID `json:"buyerId"`
	CreatedAt            time.Time          `json:"createdAt"`
	Currency             PurchaseCurrency   `json:"currency"`
	Id                   openapi_types.UUID `json:"id"`
	PaymentIntentId      string             `json:"paymentIntentId"`
	PaymentStatus        PaymentStatus      `json:"paymentStatus"`
	Reference            string             `json:"reference"`
	ReservationExpiresAt time.Time          `json:"reservationExpiresAt"`
	SellerOrders         []SellerOrder      `json:"sellerOrders"`
	Status               PurchaseStatus     `json:"status"`
	SubtotalMinor        int64              `json:"subtotalMinor"`
	TotalMinor           int64              `json:"totalMinor"`
	UpdatedAt            time.Time          `json:"updatedAt"`
}

// PurchaseCurrency defines model for Purchase.Currency.
type PurchaseCurrency string

// PurchaseItem defines model for PurchaseItem.
type PurchaseItem struct {
	Currency       PurchaseItemCurrency `json:"currency"`
	Id             openapi_types.UUID   `json:"id"`
	ImageUrl       string               `json:"imageUrl"`
	LineTotalMinor int64                `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID   `json:"productId"`
	ProductName    string               `json:"productName"`
	Quantity       int                  `json:"quantity"`
	Reviewed       bool                 `json:"reviewed"`
	Sku            string               `json:"sku"`
	UnitPriceMinor int64                `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID   `json:"variantId"`
	VariantName    string               `json:"variantName"`
}

// PurchaseItemCurrency defines model for PurchaseItem.Currency.
type PurchaseItemCurrency string

// PurchaseStatus defines model for PurchaseStatus.
type PurchaseStatus string

// Review defines model for Review.
type Review struct {
	Body           string             `json:"body"`
	BuyerId        openapi_types.UUID `json:"buyerId"`
	BuyerName      string             `json:"buyerName"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	ProductId      openapi_types.UUID `json:"productId"`
	PurchaseItemId openapi_types.UUID `json:"purchaseItemId"`
	Rating         int                `json:"rating"`
	Title          string             `json:"title"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// ReviewInput defines model for ReviewInput.
type ReviewInput struct {
	Body           string             `json:"body"`
	PurchaseItemId openapi_types.UUID `json:"purchaseItemId"`
	Rating         int                `json:"rating"`
	Title          string             `json:"title"`
}

// ReviewSummary defines model for ReviewSummary.
type ReviewSummary struct {
	Average float64  `json:"average"`
	Count   int      `json:"count"`
	Items   []Review `json:"items"`
}

// Role defines model for Role.
type Role string

// SellerOrder defines model for SellerOrder.
type SellerOrder struct {
	CancellationReason string              `json:"cancellationReason"`
	CancelledAt        *time.Time          `json:"cancelledAt,omitempty"`
	CreatedAt          time.Time           `json:"createdAt"`
	Currency           SellerOrderCurrency `json:"currency"`
	DeliveredAt        *time.Time          `json:"deliveredAt,omitempty"`
	Id                 openapi_types.UUID  `json:"id"`
	Items              []PurchaseItem      `json:"items"`
	ProcessingAt       *time.Time          `json:"processingAt,omitempty"`
	PurchaseId         openapi_types.UUID  `json:"purchaseId"`
	Reference          string              `json:"reference"`
	ShippedAt          *time.Time          `json:"shippedAt,omitempty"`
	Status             SellerOrderStatus   `json:"status"`
	StoreId            openapi_types.UUID  `json:"storeId"`
	StoreName          string              `json:"storeName"`
	SubtotalMinor      int64               `json:"subtotalMinor"`
	UpdatedAt          time.Time           `json:"updatedAt"`
}

// SellerOrderCurrency defines model for SellerOrder.Currency.
type SellerOrderCurrency string

// SellerOrderStatus defines model for SellerOrderStatus.
type SellerOrderStatus string

// Session defines model for Session.
type Session struct {
	AccessToken string           `json:"accessToken"`
	ExpiresIn   int              `json:"expiresIn"`
	TokenType   SessionTokenType `json:"tokenType"`
	User        User             `json:"user"`
}

// SessionTokenType defines model for Session.TokenType.
type SessionTokenType string

// Store defines model for Store.
type Store struct {
	CreatedAt      time.Time          `json:"createdAt"`
	Description    string             `json:"description"`
	Id             openapi_types.UUID `json:"id"`
	ModerationNote string             `json:"moderationNote"`
	Name           string             `json:"name"`
	SellerId       openapi_types.UUID `json:"sellerId"`
	Slug           string             `json:"slug"`
	Status         ModerationStatus   `json:"status"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// StoreInput defines model for StoreInput.
type StoreInput struct {
	Description string `json:"description"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// StoreProfile defines model for StoreProfile.
type StoreProfile struct {
	CreatedAt         time.Time          `json:"createdAt"`
	Description       string             `json:"description"`
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	SellerDisplayName string             `json:"sellerDisplayName"`
	Slug              string             `json:"slug"`
}

// User defines model for User.
type User struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// UserStatusInput defines model for UserStatusInput.
type UserStatusInput struct {
	Reason string     `json:"reason"`
	Status UserStatus `json:"status"`
}

// Variant defines model for Variant.
type Variant struct {
	Active     bool               `json:"active"`
	Attributes map[string]string  `json:"attributes"`
	Currency   VariantCurrency    `json:"currency"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	PriceMinor int64              `json:"priceMinor"`
	Sku        string             `json:"sku"`
	Stock      int                `json:"stock"`
}

// VariantCurrency defines model for Variant.Currency.
type VariantCurrency string

// VariantInput defines model for VariantInput.
type VariantInput struct {
	Attributes map[string]string    `json:"attributes"`
	Currency   VariantInputCurrency `json:"currency"`
	Name       string               `json:"name"`
	PriceMinor int64                `json:"priceMinor"`
	Sku        string               `json:"sku"`
	Stock      int                  `json:"stock"`
}

// VariantInputCurrency defines model for VariantInput.Currency.
type VariantInputCurrency string

// CategoryFilter defines model for CategoryFilter.
type CategoryFilter = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ImageId defines model for ImageId.
type ImageId = openapi_types.UUID

// InStock defines model for InStock.
type InStock = bool

// MaxPrice defines model for MaxPrice.
type MaxPrice = int64

// MinPrice defines model for MinPrice.
type MinPrice = int64

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// ProductSlug defines model for ProductSlug.
type ProductSlug = string

// PurchaseId defines model for PurchaseId.
type PurchaseId = openapi_types.UUID

// Search defines model for Search.
type Search = string

// StoreFilter defines model for StoreFilter.
type StoreFilter = string

// StoreId defines model for StoreId.
type StoreId = openapi_types.UUID

// StoreSlug defines model for StoreSlug.
type StoreSlug = string

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// VariantId defines model for VariantId.
type VariantId = openapi_types.UUID

// Problem400 defines model for BadRequest.
type Problem400 = Problem

// Problem409 defines model for Conflict.
type Problem409 = Problem

// Problem403 defines model for Forbidden.
type Problem403 = Problem

// Problem404 defines model for NotFound.
type Problem404 = Problem

// Problem401 defines model for Problem401.
type Problem401 = Problem

// Problem429 defines model for Problem429.
type Problem429 = Problem

// Problem503 defines model for Problem503.
type Problem503 = Health

// Problem503JSON defines model for Problem503JSON.
type Problem503JSON = Problem

// ListCatalogProductsParams defines parameters for ListCatalogProducts.
type ListCatalogProductsParams struct {
	Q        *Search         `form:"q,omitempty" json:"q,omitempty"`
	Category *CategoryFilter `form:"category,omitempty" json:"category,omitempty"`
	Store    *StoreFilter    `form:"store,omitempty" json:"store,omitempty"`
	MinPrice *MinPrice       `form:"minPrice,omitempty" json:"minPrice,omitempty"`
	MaxPrice *MaxPrice       `form:"maxPrice,omitempty" json:"maxPrice,omitempty"`
	InStock  *InStock        `form:"inStock,omitempty" json:"inStock,omitempty"`
	Page     *Page           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CheckoutParams defines parameters for Checkout.
type CheckoutParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ReceivePaymentWebhookParams defines parameters for ReceivePaymentWebhook.
type ReceivePaymentWebhookParams struct {
	XCartlabsSignature string `json:"X-Cartlabs-Signature"`
}

// UpdateAdminProductStatusJSONRequestBody defines body for UpdateAdminProductStatus for application/json ContentType.
type UpdateAdminProductStatusJSONRequestBody = ProductStatusInput

// ModerateStoreJSONRequestBody defines body for ModerateStore for application/json ContentType.
type ModerateStoreJSONRequestBody = ModerationInput

// UpdateAdminUserStatusJSONRequestBody defines body for UpdateAdminUserStatus for application/json ContentType.
type UpdateAdminUserStatusJSONRequestBody = UserStatusInput

// DemoLoginJSONRequestBody defines body for DemoLogin for application/json ContentType.
type DemoLoginJSONRequestBody = DemoLoginRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetCartItemJSONRequestBody defines body for SetCartItem for application/json ContentType.
type SetCartItemJSONRequestBody = CartItemInput

// ReceivePaymentWebhookJSONRequestBody defines body for ReceivePaymentWebhook for application/json ContentType.
type ReceivePaymentWebhookJSONRequestBody = PaymentWebhookEvent

// CancelPurchaseJSONRequestBody defines body for CancelPurchase for application/json ContentType.
type CancelPurchaseJSONRequestBody = CancellationInput

// CompleteDemoPaymentJSONRequestBody defines body for CompleteDemoPayment for application/json ContentType.
type CompleteDemoPaymentJSONRequestBody = PaymentCompletionInput

// CreateReviewJSONRequestBody defines body for CreateReview for application/json ContentType.
type CreateReviewJSONRequestBody = ReviewInput

// UpdateSellerOrderStatusJSONRequestBody defines body for UpdateSellerOrderStatus for application/json ContentType.
type UpdateSellerOrderStatusJSONRequestBody = FulfillmentInput

// CreateSellerProductJSONRequestBody defines body for CreateSellerProduct for application/json ContentType.
type CreateSellerProductJSONRequestBody = ProductInput

// UpdateSellerProductJSONRequestBody defines body for UpdateSellerProduct for application/json ContentType.
type UpdateSellerProductJSONRequestBody = ProductInput

// CreateProductImageJSONRequestBody defines body for CreateProductImage for application/json ContentType.
type CreateProductImageJSONRequestBody = ImageInput

// ReplaceProductImageJSONRequestBody defines body for ReplaceProductImage for application/json ContentType.
type ReplaceProductImageJSONRequestBody = ImageReplacementInput

// CreateProductVariantJSONRequestBody defines body for CreateProductVariant for application/json ContentType.
type CreateProductVariantJSONRequestBody = VariantInput

// UpdateSellerStoreJSONRequestBody defines body for UpdateSellerStore for application/json ContentType.
type UpdateSellerStoreJSONRequestBody = StoreInput

// CreateSellerStoreJSONRequestBody defines body for CreateSellerStore for application/json ContentType.
type CreateSellerStoreJSONRequestBody = StoreInput

// AdjustVariantInventoryJSONRequestBody defines body for AdjustVariantInventory for application/json ContentType.
type AdjustVariantInventoryJSONRequestBody = InventoryAdjustment

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H15k9s2lvhXYfE3f8whtdSOnV/cqa0pH8mkZ2Ont2XPbK3jSUHkk4SYJBgAlK306Ltv4SJBEjx1dNu1",
	"U1NJWgRxvPvC450fkDglCSSc+Vd3foooioEDlX+9QBzWhO6+xxEHKn7BiX/l/5YB3fkTP0Ex+Fd+oEf5",
	"E58FG4iRGMh3qXjGOMXJ2t/vJ/51CHFKOCTB7j9hl0+2ARQCLWazhk3FuIlP4bcMUwj9K04zsBeJ0acf",
	"IVnzjX91+eibiR/jxPz9zcS1hRit4TrM104R3xQrY/20bcUVoTHi/pWfZTj0nWskC06CD03AwvqxA1ZL",
	"QiJAiZzlFfp0Q3EATdPE5rlzczjhXz/2JTxwnMX+1TzfKU44rIGqRXDSvghODl/kJxoCbYQ50U8Pg/kN",
	"WjceIhXP7OlCWKEs4v7VpbX3S+fexbwL/Hvr3PK5c/5H84nAk15gPu9ejpIwC3gjsNL8+YHgUvMsomzd",
	"sBITj9oWcUya0WCDWDN7pcWAw7a/AESDTRNOfvObJMR87pyNEwrtAo6JIaVpU8Q5UDH0X+/Q9Pf59On7",
	"v/zxr1fT/I8//fkPfuNqjSBi+umB8BGzHILc0ad7y1pYPWNH4PR/IIpR0swi2/z5IevsxcssJQkDqQef",
	"o/AWfsuAcfHXHyis/Cv//80K1TnLh89uKFlGED+ez/39xH9BklWEgyHvPRXvfU/oEochJANe/Eq8+Jrw",
	"70mWhAPee+wrmWC2fSWMgoRDIneN0jTCAeKYJLNUDfrLr4zIjRUQdS2lnuYLKbiGwAKKUzGdUPbJFkU4",
	"9KiGrr2Ry/vYSEAhhIRjFDGPUI8BY2KAva+vzrsvlq1WOMCQcC8FGuP6hh6fc0O3wEhGA/ASwr2VpDR7",
	"L0/PuZcFRxy8wLCYtY9HZ93Hs4xvBNGo+T0hPeOUMw8+BQAhhP5EW7lSmNwCp7vps5VWODWdWlgE++JE",
	"T1rJbthJfgAU8Y3rIC8hhSQUpreXJWiLcISWEfilbfx98dPrewRuhGPMgVb3twC6xQG8tX7tKwCfzL9y",
	"z2A2NWAiCZz9xH9DyCuU7LTSYP2F8SMp/d8mKOMbQvHvMESQX0oVqWEq3nsWxjj5aStOBh/FDyklKVCO",
	"lVpDAcdbWEAUAZVmOhts4E8E8inZQiitjjETBBmlguTEq5CIYe/865e3/vuaXhakEeEtUAhHb3dNCWOv",
	"QJiiSYgZvMIJoSPmSbNlhNkGQm1Ms1FzKIt4zLvCmmJj/LHCKnqnJ6nh0HU6e7cTF+XUkdMEbAvlBY7J",
	"8ldQMlwSrV5XUmkYYsH6KLqxqHeFIgaTCkHnkYgOcWPiGpL8KCAO4TNeAmaIOEw5jsF3UqEloO7qzyFZ",
	"ERq0zplkkZZSyjZtnOO5PEzf4TEk/BaQlr2W8/PE4fxMfBz2sIYnKjAiAYw5xKyHMJduqnjL3+fzIUqR",
	"hLgy1R1wY9pnqT/giGfMFhA5gfoTn2VMqq3QKTJY4XF1HlSOfd24PduvGucjTfwsDYeSm/Zp+iNAO0l1",
	"2FfYXwKh8DmL803smJ5E18R4jTbt54ix9phTi4smS6xRonGbD20gNQoI4WoOlQ4jOB2zNEK7RpKAGOGo",
	"NJ36ZTyvURJBF35viTJ6CrZoGy0gtVAjx9Cfi2bMIW3w6K1bNDEAo1mI+XdbbU7WjZQGOYsCTmhP1pZj",
	"G/Eon95q0BsZs8x2MjDNpJrzJz4ShCd+2DEOsVPajKExxFEzJZfkfQGxvtSkvbXrYcPf7FIXnFykUEBu",
	"YlBVmae0C31cG1AugniBkgCiSJr810maDTUEaKMOtFIEj7poXc/i3iB10OoQUxYPUEn9Rb/Yl7TiXIqX",
	"ZUtOOIrG2rzy5f/KUMIxl2dsH34UUZODNAdF9RzVfXUJGwGiaw5xHX2555dncI7nuUit+JaWlUVG8ZTC",
	"CsQsTtkQ4QTeHIKy1E4pdBKbHt0oJtNy4qD2/DcXbVy69sU+ZM4ZsgRzmXMae+CtHSDuPLAe3XDgCj3a",
	"sWU7FWNDrQyj8gLq1BYpWACbVImvBooaMXS4UYbMx4jPEh5NBuvp084Elg2tfI6mzSkxVWPCXMz1lneS",
	"mfdyc9fqnUuH7DueG3CQFK1AqWJ9azpRR68u5QZk4fFW4NjvrEOdMZeMtj0E1yZfQkx+JGucWEmUIcq8",
	"t0lc1d/iR9eGvs+iFY6iGBJ+mHWR53p9f9LtbjvcWEoCYEw8n/hsg9MUQjuSIj0xaQo5vdsaMcn5XSfW",
	"Md8alYQm4qv/dkPBQR61FeqHIx/kUdYUhQfuXtVtjMAUivgb+MSrmeCvXdhJCcPG1egwbDrUuBUb+OOG",
	"85T99Wo2+/fs3b9m7//UafVkUjGYjTdC4xbSCCnn+tSAGXzcq9mMAvv554sgIlmIE0R34g8Sz/49U9GB",
	"2VHgkAiPkdDds/DXjPEYkqFQCCFSvldCuEW58/d7F9qdTsWjilNx2XUuteakzbk4QFY2ByTsPT957KJ/",
	"xNhHQstqI/9xMrjYyj602UQ+nevYr0gIdLTLlxAOvYKedUFlwt8SK2I3A8TVRC3cfp5FXfBDEiqp329x",
	"mdjHK50Fq8vxJQl3Tjk9IiCxkXp2iJvS09b4gFVdQu0BBTRohxzzqG+AQi5qXpkoQOkzdkUhbtBOCJUX",
	"JE4jGEuXJOMBiUuBJZYFeWJ4hXAv3W6madlnG5U5lpz48CnF3UZGPv8/Ybkh5EMepztx6LU1LOZWajHJ",
	"Ej7Wcxzkzcvcd++ommGdboo189pvTUoH63D7erIi1xG+nFIUii9sOjG/9SXRYqVy7Fdi0km3RYJ9kNLm",
	"Wsc5IC115nXYkUXKfdonJaf28dwd9mqQNgUU+0rKCsA0rIxoajGAdUrtZX70zy8p+vnmGkOKVtxOiguO",
	"pMEGb/8v/fiA04/9008lIjqdH9WTAx6IHyo3V3bCrL21gXGEkWTw3ZNRKrKmbPLPW6JcVRy1ZoMKITG6",
	"INoGqHXGNqpugay55nBIwNTU/mdxjJSsr4rMVK/iSCZY1yEaskOuR1XC0sFNfTEjLe5QqBlaAKAs3JMl",
	"BC9tlrn4888/Ly7+7PfyIAsdYKuJ/j5kSzCggrB6znGMerdM3YMUtU5o1R8Wl6Cql5sm+bWiZkO9Tlxj",
	"9PiJlWlXJLwc0m/QbmVYlNKdxU2xHNRO+tBleY6YgKhf6ClRRxh8J0h2a4/j2vKumsYsetW+lD3jDl9M",
	"PGVAtzLE8p30jdkQgLBKIW0veWzVUPbIYfU6syaI4tBHyfuPffkoVQC2VWPI2jL/yjRRp6MSXzmrB8wf",
	"TgqooHaQaWkuvTkLDk7AQl9EnUH/OgIKorQdQrem+RyrDHC1vMBRdqB1Sv/iggG1BBZM2wi6Mdj4i2Y+",
	"yYbYiiP9MjjueAvm3sIAS89Ewss5mq4kzWSQtpRjG6l3hC7Fg/imL5dZsqfnKxRx8V+lENmkgwXz8Fgp",
	"QdQN8KMohkIZFDipnbzMT/qMtZRAf6Gu6HKMGzKWOB80Kit4qQHfDfBmwDa6OmgLVDunBb2QbCkndZ6y",
	"EN5JFi/VIQMRS+8Orgxzq9XOO0Ne5gRmF2YZJzD6lSO7BKdtVDocxqK2trgrUpdiRjQP8glO60bkdTEn",
	"kK0Dwyi2XddltxdVPkP2nZYaKhyUZcpri4as38/bsEjNcjgeSLHdkZRMpXNFYUe7q/eKCxDNTocJgjmY",
	"cYgmqkO/l0F2WNWZWFbdQndc1hATvyEfoOFmnPKprpNuy56LSd5U0pTPAVGgzj1l+kJQ11WYuky29mwv",
	"a+9WT+9EgSljPXE6vDHkfTk/5G5fnBepvNYFNL2C5/MewXNJm32lwIF5rX7CqlaRcywJkZ+1Z76qAvVB",
	"LC9lzgjbczAFjcX7MaOqw/IkEjY3lKxw9Bmz5EH89rLjxiI7ccy7QvC1PXXVXJl7nRXafcD3MAdekGw6",
	"dF1/q0v2nRUGxcsPKDHW90LqiISYKS8Ydk4NTGeYEHFO8TLjh5bAnyCc65IFPWIr6SHBTR01tZb8+nG3",
	"9OlzZc6pOmXYUgsRCxOlQ1TvAcq0mEZpC42Mqoy/B2L4orE8FsF1vEolF2QU891CyBLdnE36BKJNkPhr",
	"Kf/63sDi7/98Yxr3SaaXTwtGE1UxKvC0osA2Lwj5gKFmLJkcPCaJtxAbEE2nxEjvI+Yb7wbxzX/MLrwf",
	"SYAi74c3b268jAHzAkR5hJbsF6pm91hAUgg9TjxUbmpEiYDIhUz6+le+mrxoavfLLz8QxqfV+YpjoBSL",
	"VqmyexJOVsRxAlGUEHi33y3eiIZZnKJAtO+i3gs9qfcRlh5KQu/ZzbVnNXRiF3ng7srPBz+7uRb5B6DK",
	"DfTnF48vZL87kkKCUuxf+V9dzC++UkVIG4mnmYxXzVAWYj6Frek4uwbJoYK5VO1/6F/5P2LGi6YASiFY",
	"/fgetXapq7eeOqRgpthGd0FbQyzP1dQqxNxTQPAS+AiMeytMVQc83WKuvelT0SBQsoUJmUrI5TMW19wk",
	"ajnNGPeQtbbALVozsXnZVQMzrrDgvxfTapQRq4OUE11/A15uNXUgvlrxUVrIAdtXiH4ALm9HefnODwXr",
	"34B7sT2xOn+y9mRYpycgU6tXVDPdW/2P7pfyrY0ckfa/U11fxFVnL8JMAJEpQRohLshWmbtCskhRJSoP",
	"HTSel1lJ0s5NZM/AWEo3qwVNFUNOxMzu8kzRflZYsyniquFsGVtvpaNug8mqQCj6aL9zg7kYMisa/+7f",
	"51Xsz3Wu6Chc4yig25dRyGkG+1PzbU5NdbJQwAw9qJOH4t55N/dafVpHMPzE170029/IO6zKF552v5D3",
	"gC1T8UKRrGgzSgEnTDaz1OSXn7yNaIvWIO2yJO/qdm+SpKEjyWgRok7koY8ISxlMqLdBW/FfW6DFLTmH",
	"1FAwk7KhNLQbzrM7He3fz4roXYtw0LFGWOjm0cMkgukTfSp5UL1reWZhoAmijtl/SKSA5gp1HdJjhnwG",
	"8mcJ/XLmXTGvnrUN8XmPxXb+eiuHHQitAR7qCC2uEh/HM1/FnFOGViA8HSql1XEsVwnyskXciaHZnWot",
	"PkxjW1Goocyp25wP5034hMRVUjvu5t9CKuOhJfMyJREOdt4WE5UaZEXy4MoKB+4nPfmtGiO8D92vk2+N",
	"ij/TNPqFa3oZtRKqXp63gbgzvpmFEJNpRNZYaRnCHDIo76zin0ZN1Dq3nFtPmP7rrX2hhQ/AvFAwp3K9",
	"cOAJ6HkoMGU2Vv/tBfBpEehp/qTFfhxhPepBJ9X20PuJ/6TPSs09qu3YmH/17r1NfjakFKBi4ulmjYb6",
	"rkPQ3ZoKAuygvVPS3edAc996Jq6ng4EMDqK0EVLvsvuVUivxz4A+ZSBAps+kX2/1H+kgVZLxVloVz2tU",
	"87geKdWhYG+FYhztPApb8gHC6gHuqiHjd+/3pUPdyvc8Wpqt4xR6cPMx9JqGQu+HCfQjjxIu2OAQkh9M",
	"v0ORILeYI4HlcGvAQqC7ejYFOWXXzxNCXc7vAPkLmRvhMqOgQ2V4K4IFOAAV/pIZk2MEOWWVqVpoTUkm",
	"8hXLnZfXnBrAyZ0WQJtJ32F2l99V2Ov2SsChDslbiMkW8tZ9Q83v4htAygI/MzKMvSqJ5UCnVEFCgRsr",
	"WFQgPPF1CrMMwgXwo8Hv+Oq73HvyzPq7P95GaNwzeg3PQu0xKJcwpxHPutfjZEeOIrLul2t4oQbbX3kY",
	"FqZSn2LbTzpHVj4l2eMN+8NsPYbnHzPsMxZ96j3WfM+xx9Ab1YSk1zh55f2k8stuGuBgh5s8f1JkTCiJ",
	"dVjURN3YKE5pMfYUxajsTZAvXSJlSZIN1Dy7E3Vm+3YlbdP02FyMvKp9Dvzonj59MOSp1kcuPI1URA1I",
	"EoZAGUN66aF4mqm7hO1CSAPiVg99sAgr305yfhtNDPA0HKVhpiOZBgxHxZIMmOZkkFfvT811hXzVAmkG",
	"xmWk5QmOnqx1QErjECxZ0VOrWtd/NH/09XT+zfTy0ZvL+dVc/P9//CpqfkBJGKMQvDUhoZZ0kazXidEH",
	"oKr2Rpxyfvn0m6er+Xw6n8/n0/8v/vHNXP+p/nc5LypzXmcMJRxR5L2gaCXlmKMM118gik2J7JWfmJem",
	"gXqpdxi3VN/sik/oXpKGeSVivdS8cA6bp0Oq5OTq3GGLdBHGA4ZOa8YMu8dkp91o5Uj5FutgnQJBM7UX",
	"2MBoAOsGgg+VuElVomVMpFUZisGrfJnbo8AzmjCPULzGCYq8XPAIF5Vk3FPdFMQE/CMOQDBZGWsvzA6G",
	"CpPKx8QdEuXyeIpaH8uto/WRVbBKXrTyVBdHTwup0Xw3yHU4ToTOckwF5sDDpseyPKA6kY4GeMS0w3B4",
	"IRvZb3wW6ZrrJoXyI95CAoydMqjS/LnLG3UPzkNym22cJenU0/fmvKjYtTm6XqR0eAoo3LWd/hZQiO/v",
	"+C+t3u+e2ux4MuoBvrD4uii1Tu4EYdxKNjoe9lZl0E4GuqaMpQnHFRnLUYHMkmIM7DkbA5SJ1QS6XRe+",
	"Lo28R3Vob+SIKrF0vhOU0IYZlSVosr4hqQDTYKcMZIUirQTY7KNql9wWzQ8Ab6HcXbmuCbE4rgqxF4bn",
	"f09NLfZ0gdcJ4hmFQR/sP1WdoaNVdK/4nyMTI98WOVxIuaoIQpEUU0YQH6Bbx2TOjmYIa8R7DK8TUfhB",
	"hG7RtoOsy7ZITAM0py77k7HNHnU+6h4ZvzCbjsb0z2VyIofBCdh+WV7BRkT+WwUTs7uiP0Cr95wDZHCE",
	"I5//xBGpPoauTD+VLEBpGuI4zriUmDJGzRKUsg3h7NAMSZGTSgvwDcPJTDUzaBbE6muDx0PPKRIq1e8h",
	"njmp0kYaL0yviLIDKLw/TiiEhRPxZZZ3qfMXh1/CSgQ17Ns3S1jjZLg0EcZEs3MuirOmJIl2HiRhSnDC",
	"vxWacYtDoB6DJGRGw2hTxOzMnMjhj6tPXYCY+sZqG/LA2KHhwxwPiCeKuMCKA80RwClKdAftL4UVjhx4",
	"MBRYsoqa7SErv9Ag22XIQrfnOg012u3gepHg5ZGXbiukr2YDzkh34yWqTqRIS0KG6vPkRsnyaExsqEEz",
	"krfibbSUF+XGrvd3Q6bcBvhY92QsYFVNskMtZW37LSEiyVpdhDTIqd6sqCq7Enpmd/LfA8r3602vhqqo",
	"n9SKJ9NPte9Lnr2E1aKm5kqYEi99kabZs3ArjDMRO1BOgEc+Js1SxMJbmVR7FdMoqD+Em7uV0oKjyRNz",
	"Ng3F5a7M8a77duq5o85DQUtVuLVo7hJQ/ZNejr0XDd5ZBfJS5IgNAM/EpWWLrJT0SXNM1BDp4Bf7PnVb",
	"aKSK5cOuT99XwU5uuyr2OC/ODg+zBOXtdyN80kdPHwupD4Htz0hLRkeHR2H/8YSh9nE498/0F9OaPbVn",
	"asCXIQr0YSpC4JyWj9qA1SbjANwVH+VrU9Wlz6g9PHa3PiJ+PzpeAabZrPKwGvB5lKanpU2PJqrZnfx3",
	"x42Rl/L3YxFYj6JvtSeXEHnc2B5MgcJTZwg/Bzy+BEvflxCqyn1InIo+YRRihBPh45vv/zUZ8pkzzS0v",
	"MNwX8k4kSGrf378fA6JRpuj9Vfn0/AaE3oiTyEydYLBBydqmrzHyRGu6Zi2l6+m/DAOjdjngUFmgJyy8",
	"AGV5iqqLii0jcr0QYsShdKO1N6LsD8r2sCdMv9eHZ1GUuoye2aYwUGkxJ7ZmyNl5XocM0spG2mmFmUb6",
	"7UECc/ng/L2JFqVY1+H+dkO0XK7P+rrXBTiOT99Wq/mH0h8qD12LAd96MeJAMYqUBgGma9JFLkJ//eLe",
	"XeY29HbGPR8Sdi/PwGHigceyZYy5wHKtTdtZSulbop+NyLTkmFFv9m34WVEC05zdehb+mjGeKxXzwsO7",
	"3p3vTe047l3kOT+H+jMioqT+DvF1xRnNbFYtk0ubVftT2L2pdXMKca1CI1J+v92foRTPtpcSW3rG2jWc",
	"LOE4Bk9dLLgoyoBNcf/krrlTDSaJ6hGhul8w6/W8urw+ga3svBglaC19Hevlhbkf3NBr2u5npi8lWW+b",
	"m0hNK0+Vv6BfbNiBHOmYwm4BbMsPCQerJ6w1l2q/VZ/qedEPQ7xsrkyVTkK548XSzSCmzyQT8bJSwZrA",
	"jHTB8pVdGxzk9U5q0lJxV2lG9YJrwpeNde3W++W69v37/f8OAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
