// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AdminOverviewCurrency.
const (
	AdminOverviewCurrencyIDR AdminOverviewCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the AdminOverviewCurrency enum.
func (e AdminOverviewCurrency) Valid() bool {
	switch e {
	case AdminOverviewCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for AdminProductStatus.
const (
	AdminProductStatusPublished AdminProductStatus = "published"
	AdminProductStatusSuspended AdminProductStatus = "suspended"
)

// Valid indicates whether the value is a known member of the AdminProductStatus enum.
func (e AdminProductStatus) Valid() bool {
	switch e {
	case AdminProductStatusPublished:
		return true
	case AdminProductStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for AuditEventActorRole.
const (
	AuditEventActorRoleAdmin  AuditEventActorRole = "admin"
	AuditEventActorRoleBuyer  AuditEventActorRole = "buyer"
	AuditEventActorRoleSeller AuditEventActorRole = "seller"
	AuditEventActorRoleSystem AuditEventActorRole = "system"
)

// Valid indicates whether the value is a known member of the AuditEventActorRole enum.
func (e AuditEventActorRole) Valid() bool {
	switch e {
	case AuditEventActorRoleAdmin:
		return true
	case AuditEventActorRoleBuyer:
		return true
	case AuditEventActorRoleSeller:
		return true
	case AuditEventActorRoleSystem:
		return true
	default:
		return false
	}
}

// Defines values for CartCurrency.
const (
	CartCurrencyIDR CartCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartCurrency enum.
func (e CartCurrency) Valid() bool {
	switch e {
	case CartCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for CartItemCurrency.
const (
	CartItemCurrencyIDR CartItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartItemCurrency enum.
func (e CartItemCurrency) Valid() bool {
	switch e {
	case CartItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for FulfillmentInputStatus.
const (
	FulfillmentInputStatusCancelled  FulfillmentInputStatus = "cancelled"
	FulfillmentInputStatusDelivered  FulfillmentInputStatus = "delivered"
	FulfillmentInputStatusProcessing FulfillmentInputStatus = "processing"
	FulfillmentInputStatusShipped    FulfillmentInputStatus = "shipped"
)

// Valid indicates whether the value is a known member of the FulfillmentInputStatus enum.
func (e FulfillmentInputStatus) Valid() bool {
	switch e {
	case FulfillmentInputStatusCancelled:
		return true
	case FulfillmentInputStatusDelivered:
		return true
	case FulfillmentInputStatusProcessing:
		return true
	case FulfillmentInputStatusShipped:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ModerationInputStatus.
const (
	ModerationInputStatusApproved ModerationInputStatus = "approved"
	ModerationInputStatusRejected ModerationInputStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationInputStatus enum.
func (e ModerationInputStatus) Valid() bool {
	switch e {
	case ModerationInputStatusApproved:
		return true
	case ModerationInputStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ModerationStatus.
const (
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusRejected ModerationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationStatus enum.
func (e ModerationStatus) Valid() bool {
	switch e {
	case ModerationStatusApproved:
		return true
	case ModerationStatusPending:
		return true
	case ModerationStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PaymentCompletionInputOutcome.
const (
	PaymentCompletionInputOutcomeFailed    PaymentCompletionInputOutcome = "failed"
	PaymentCompletionInputOutcomeSucceeded PaymentCompletionInputOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentCompletionInputOutcome enum.
func (e PaymentCompletionInputOutcome) Valid() bool {
	switch e {
	case PaymentCompletionInputOutcomeFailed:
		return true
	case PaymentCompletionInputOutcomeSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatus.
const (
	PaymentStatusCancelled PaymentStatus = "cancelled"
	PaymentStatusExpired   PaymentStatus = "expired"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusSucceeded PaymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusCancelled:
		return true
	case PaymentStatusExpired:
		return true
	case PaymentStatusFailed:
		return true
	case PaymentStatusPending:
		return true
	case PaymentStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventDataCurrency.
const (
	PaymentWebhookEventDataCurrencyIDR PaymentWebhookEventDataCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventDataCurrency enum.
func (e PaymentWebhookEventDataCurrency) Valid() bool {
	switch e {
	case PaymentWebhookEventDataCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventType.
const (
	PaymentWebhookEventTypePaymentFailed    PaymentWebhookEventType = "payment.failed"
	PaymentWebhookEventTypePaymentSucceeded PaymentWebhookEventType = "payment.succeeded"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventType enum.
func (e PaymentWebhookEventType) Valid() bool {
	switch e {
	case PaymentWebhookEventTypePaymentFailed:
		return true
	case PaymentWebhookEventTypePaymentSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ProductDetailStatus.
const (
	ProductDetailStatusArchived  ProductDetailStatus = "archived"
	ProductDetailStatusDraft     ProductDetailStatus = "draft"
	ProductDetailStatusPublished ProductDetailStatus = "published"
	ProductDetailStatusSuspended ProductDetailStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProductDetailStatus enum.
func (e ProductDetailStatus) Valid() bool {
	switch e {
	case ProductDetailStatusArchived:
		return true
	case ProductDetailStatusDraft:
		return true
	case ProductDetailStatusPublished:
		return true
	case ProductDetailStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for ProductStatusInputStatus.
const (
	ProductStatusInputStatusPublished ProductStatusInputStatus = "published"
	ProductStatusInputStatusSuspended ProductStatusInputStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProductStatusInputStatus enum.
func (e ProductStatusInputStatus) Valid() bool {
	switch e {
	case ProductStatusInputStatusPublished:
		return true
	case ProductStatusInputStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseCurrency.
const (
	PurchaseCurrencyIDR PurchaseCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseCurrency enum.
func (e PurchaseCurrency) Valid() bool {
	switch e {
	case PurchaseCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseItemCurrency.
const (
	PurchaseItemCurrencyIDR PurchaseItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseItemCurrency enum.
func (e PurchaseItemCurrency) Valid() bool {
	switch e {
	case PurchaseItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseStatus.
const (
	PurchaseStatusCancelled      PurchaseStatus = "cancelled"
	PurchaseStatusExpired        PurchaseStatus = "expired"
	PurchaseStatusPaid           PurchaseStatus = "paid"
	PurchaseStatusPaymentFailed  PurchaseStatus = "payment_failed"
	PurchaseStatusPendingPayment PurchaseStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the PurchaseStatus enum.
func (e PurchaseStatus) Valid() bool {
	switch e {
	case PurchaseStatusCancelled:
		return true
	case PurchaseStatusExpired:
		return true
	case PurchaseStatusPaid:
		return true
	case PurchaseStatusPaymentFailed:
		return true
	case PurchaseStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	RoleAdmin  Role = "admin"
	RoleBuyer  Role = "buyer"
	RoleSeller Role = "seller"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case RoleAdmin:
		return true
	case RoleBuyer:
		return true
	case RoleSeller:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderCurrency.
const (
	SellerOrderCurrencyIDR SellerOrderCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the SellerOrderCurrency enum.
func (e SellerOrderCurrency) Valid() bool {
	switch e {
	case SellerOrderCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderStatus.
const (
	SellerOrderStatusCancelled      SellerOrderStatus = "cancelled"
	SellerOrderStatusDelivered      SellerOrderStatus = "delivered"
	SellerOrderStatusPaid           SellerOrderStatus = "paid"
	SellerOrderStatusPendingPayment SellerOrderStatus = "pending_payment"
	SellerOrderStatusProcessing     SellerOrderStatus = "processing"
	SellerOrderStatusShipped        SellerOrderStatus = "shipped"
)

// Valid indicates whether the value is a known member of the SellerOrderStatus enum.
func (e SellerOrderStatus) Valid() bool {
	switch e {
	case SellerOrderStatusCancelled:
		return true
	case SellerOrderStatusDelivered:
		return true
	case SellerOrderStatusPaid:
		return true
	case SellerOrderStatusPendingPayment:
		return true
	case SellerOrderStatusProcessing:
		return true
	case SellerOrderStatusShipped:
		return true
	default:
		return false
	}
}

// Defines values for SessionTokenType.
const (
	Bearer SessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionTokenType enum.
func (e SessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive:
		return true
	case UserStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for VariantCurrency.
const (
	VariantCurrencyIDR VariantCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantCurrency enum.
func (e VariantCurrency) Valid() bool {
	switch e {
	case VariantCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for VariantInputCurrency.
const (
	VariantInputCurrencyIDR VariantInputCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantInputCurrency enum.
func (e VariantInputCurrency) Valid() bool {
	switch e {
	case VariantInputCurrencyIDR:
		return true
	default:
		return false
	}
}

// AdminOverview defines model for AdminOverview.
type AdminOverview struct {
	ActiveSellerOrders    int64                 `json:"activeSellerOrders"`
	ApprovedStores        int64                 `json:"approvedStores"`
	Currency              AdminOverviewCurrency `json:"currency"`
	DeliveredOrders       int64                 `json:"deliveredOrders"`
	GrossMerchandiseMinor int64                 `json:"grossMerchandiseMinor"`
	PublishedProducts     int64                 `json:"publishedProducts"`
	Purchases             int64                 `json:"purchases"`
	Users                 int64                 `json:"users"`
}

// AdminOverviewCurrency defines model for AdminOverview.Currency.
type AdminOverviewCurrency string

// AdminProduct defines model for AdminProduct.
type AdminProduct struct {
	Category          Category           `json:"category"`
	CreatedAt         time.Time          `json:"createdAt"`
	Description       string             `json:"description"`
	EnforcedAt        *time.Time         `json:"enforcedAt"`
	EnforcedBy        *string            `json:"enforcedBy"`
	EnforcementReason string             `json:"enforcementReason"`
	Id                openapi_types.UUID `json:"id"`
	Images            []ProductImage     `json:"images"`
	Name              string             `json:"name"`
	Slug              string             `json:"slug"`
	Status            AdminProductStatus `json:"status"`
	StoreId           openapi_types.UUID `json:"storeId"`
	StoreName         *string            `json:"storeName,omitempty"`
	StoreSlug         string             `json:"storeSlug"`
	UpdatedAt         time.Time          `json:"updatedAt"`
	Variants          []Variant          `json:"variants"`
}

// AdminProductStatus defines model for AdminProduct.Status.
type AdminProductStatus string

// AdminUser defines model for AdminUser.
type AdminUser struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
	Status      UserStatus          `json:"status"`
	UpdatedAt   time.Time           `json:"updatedAt"`
}

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action       string                 `json:"action"`
	ActorId      *openapi_types.UUID    `json:"actorId,omitempty"`
	ActorName    *string                `json:"actorName,omitempty"`
	ActorRole    AuditEventActorRole    `json:"actorRole"`
	CreatedAt    time.Time              `json:"createdAt"`
	Data         map[string]interface{} `json:"data"`
	Id           openapi_types.UUID     `json:"id"`
	ResourceId   openapi_types.UUID     `json:"resourceId"`
	ResourceType string                 `json:"resourceType"`
}

// AuditEventActorRole defines model for AuditEvent.ActorRole.
type AuditEventActorRole string

// CancellationInput defines model for CancellationInput.
type CancellationInput struct {
	Reason string `json:"reason"`
}

// Cart defines model for Cart.
type Cart struct {
	Currency      CartCurrency       `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	Stores        []CartStore        `json:"stores"`
	SubtotalMinor int64              `json:"subtotalMinor"`
	TotalQuantity int                `json:"totalQuantity"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// CartCurrency defines model for Cart.Currency.
type CartCurrency string

// CartItem defines model for CartItem.
type CartItem struct {
	AvailableStock int                `json:"availableStock"`
	Currency       CartItemCurrency   `json:"currency"`
	ImageUrl       string             `json:"imageUrl"`
	LineTotalMinor int64              `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID `json:"productId"`
	ProductName    string             `json:"productName"`
	ProductSlug    string             `json:"productSlug"`
	Quantity       int                `json:"quantity"`
	Sku            string             `json:"sku"`
	UnitPriceMinor int64              `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID `json:"variantId"`
	VariantName    string             `json:"variantName"`
}

// CartItemCurrency defines model for CartItem.Currency.
type CartItemCurrency string

// CartItemInput defines model for CartItemInput.
type CartItemInput struct {
	Quantity int `json:"quantity"`
}

// CartStore defines model for CartStore.
type CartStore struct {
	Items         []CartItem         `json:"items"`
	StoreId       openapi_types.UUID `json:"storeId"`
	StoreName     string             `json:"storeName"`
	SubtotalMinor int64              `json:"subtotalMinor"`
}

// Category defines model for Category.
type Category struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// DemoLoginRequest defines model for DemoLoginRequest.
type DemoLoginRequest struct {
	Role Role `json:"role"`
}

// FulfillmentInput defines model for FulfillmentInput.
type FulfillmentInput struct {
	Reason *string                `json:"reason,omitempty"`
	Status FulfillmentInputStatus `json:"status"`
}

// FulfillmentInputStatus defines model for FulfillmentInput.Status.
type FulfillmentInputStatus string

// Health defines model for Health.
type Health struct {
	Dependencies *map[string]string `json:"dependencies,omitempty"`
	Status       HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImageInput defines model for ImageInput.
type ImageInput struct {
	AltText  string `json:"altText"`
	Position *int   `json:"position,omitempty"`
	Url      string `json:"url"`
}

// ImageReplacementInput defines model for ImageReplacementInput.
type ImageReplacementInput struct {
	AltText string `json:"altText"`
	Url     string `json:"url"`
}

// InventoryAdjustment defines model for InventoryAdjustment.
type InventoryAdjustment struct {
	Delta  int    `json:"delta"`
	Reason string `json:"reason"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ModerationInput defines model for ModerationInput.
type ModerationInput struct {
	Note   string                `json:"note"`
	Status ModerationInputStatus `json:"status"`
}

// ModerationInputStatus defines model for ModerationInput.Status.
type ModerationInputStatus string

// ModerationStatus defines model for ModerationStatus.
type ModerationStatus string

// Notification defines model for Notification.
type Notification struct {
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Kind      string             `json:"kind"`
	ReadAt    *time.Time         `json:"readAt,omitempty"`
	Title     string             `json:"title"`
}

// PaymentCompletionInput defines model for PaymentCompletionInput.
type PaymentCompletionInput struct {
	Outcome PaymentCompletionInputOutcome `json:"outcome"`
}

// PaymentCompletionInputOutcome defines model for PaymentCompletionInput.Outcome.
type PaymentCompletionInputOutcome string

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PaymentWebhookEvent defines model for PaymentWebhookEvent.
type PaymentWebhookEvent struct {
	CreatedAt time.Time `json:"createdAt"`
	Data      struct {
		AmountMinor int64                           `json:"amountMinor"`
		Currency    PaymentWebhookEventDataCurrency `json:"currency"`
		IntentId    openapi_types.UUID              `json:"intentId"`
		Reference   string                          `json:"reference"`
	} `json:"data"`
	Id   openapi_types.UUID      `json:"id"`
	Type PaymentWebhookEventType `json:"type"`
}

// PaymentWebhookEventDataCurrency defines model for PaymentWebhookEvent.Data.Currency.
type PaymentWebhookEventDataCurrency string

// PaymentWebhookEventType defines model for PaymentWebhookEvent.Type.
type PaymentWebhookEventType string

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// ProductDetail defines model for ProductDetail.
type ProductDetail struct {
	Category    Category            `json:"category"`
	CreatedAt   time.Time           `json:"createdAt"`
	Description string              `json:"description"`
	Id          openapi_types.UUID  `json:"id"`
	Images      []ProductImage      `json:"images"`
	Name        string              `json:"name"`
	Slug        string              `json:"slug"`
	Status      ProductDetailStatus `json:"status"`
	StoreId     openapi_types.UUID  `json:"storeId"`
	StoreName   *string             `json:"storeName,omitempty"`
	StoreSlug   string              `json:"storeSlug"`
	UpdatedAt   time.Time           `json:"updatedAt"`
	Variants    []Variant           `json:"variants"`
}

// ProductDetailStatus defines model for ProductDetail.Status.
type ProductDetailStatus string

// ProductImage defines model for ProductImage.
type ProductImage struct {
	AltText  string             `json:"altText"`
	Id       openapi_types.UUID `json:"id"`
	Position int                `json:"position"`
	Url      string             `json:"url"`
}

// ProductInput defines model for ProductInput.
type ProductInput struct {
	CategoryId  openapi_types.UUID `json:"categoryId"`
	Description string             `json:"description"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
}

// ProductPage defines model for ProductPage.
type ProductPage struct {
	Items    []ProductSummary `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// ProductStatusInput defines model for ProductStatusInput.
type ProductStatusInput struct {
	Reason string                   `json:"reason"`
	Status ProductStatusInputStatus `json:"status"`
}

// ProductStatusInputStatus defines model for ProductStatusInput.Status.
type ProductStatusInputStatus string

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	Category      Category           `json:"category"`
	Currency      string             `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	ImageUrl      string             `json:"imageUrl"`
	InStock       bool               `json:"inStock"`
	MinPriceMinor int64              `json:"minPriceMinor"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	StoreName     string             `json:"storeName"`
	StoreSlug     string             `json:"storeSlug"`
}

// Purchase defines model for Purchase.
type Purchase struct {
	BuyerId              openapi_types.UUID `json:"buyerId"`
	CreatedAt            time.Time          `json:"createdAt"`
	Currency             PurchaseCurrency   `json:"currency"`
	Id                   openapi_types.UUID `json:"id"`
	PaymentIntentId      string             `json:"paymentIntentId"`
	PaymentStatus        PaymentStatus      `json:"paymentStatus"`
	Reference            string             `json:"reference"`
	ReservationExpiresAt time.Time          `json:"reservationExpiresAt"`
	SellerOrders         []SellerOrder      `json:"sellerOrders"`
	Status               PurchaseStatus     `json:"status"`
	SubtotalMinor        int64              `json:"subtotalMinor"`
	TotalMinor           int64              `json:"totalMinor"`
	UpdatedAt            time.Time          `json:"updatedAt"`
}

// PurchaseCurrency defines model for Purchase.Currency.
type PurchaseCurrency string

// PurchaseItem defines model for PurchaseItem.
type PurchaseItem struct {
	Currency       PurchaseItemCurrency `json:"currency"`
	Id             openapi_types.UUID   `json:"id"`
	ImageUrl       string               `json:"imageUrl"`
	LineTotalMinor int64                `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID   `json:"productId"`
	ProductName    string               `json:"productName"`
	Quantity       int                  `json:"quantity"`
	Sku            string               `json:"sku"`
	UnitPriceMinor int64                `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID   `json:"variantId"`
	VariantName    string               `json:"variantName"`
}

// PurchaseItemCurrency defines model for PurchaseItem.Currency.
type PurchaseItemCurrency string

// PurchaseStatus defines model for PurchaseStatus.
type PurchaseStatus string

// Review defines model for Review.
type Review struct {
	Body           string             `json:"body"`
	BuyerId        openapi_types.UUID `json:"buyerId"`
	BuyerName      string             `json:"buyerName"`
	CreatedAt      time.Time          `json:"createdAt"`
	Id             openapi_types.UUID `json:"id"`
	ProductId      openapi_types.UUID `json:"productId"`
	PurchaseItemId openapi_types.UUID `json:"purchaseItemId"`
	Rating         int                `json:"rating"`
	Title          string             `json:"title"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// ReviewInput defines model for ReviewInput.
type ReviewInput struct {
	Body           string             `json:"body"`
	PurchaseItemId openapi_types.UUID `json:"purchaseItemId"`
	Rating         int                `json:"rating"`
	Title          string             `json:"title"`
}

// ReviewSummary defines model for ReviewSummary.
type ReviewSummary struct {
	Average float64  `json:"average"`
	Count   int      `json:"count"`
	Items   []Review `json:"items"`
}

// Role defines model for Role.
type Role string

// SellerOrder defines model for SellerOrder.
type SellerOrder struct {
	CancellationReason string              `json:"cancellationReason"`
	CancelledAt        *time.Time          `json:"cancelledAt,omitempty"`
	CreatedAt          time.Time           `json:"createdAt"`
	Currency           SellerOrderCurrency `json:"currency"`
	DeliveredAt        *time.Time          `json:"deliveredAt,omitempty"`
	Id                 openapi_types.UUID  `json:"id"`
	Items              []PurchaseItem      `json:"items"`
	ProcessingAt       *time.Time          `json:"processingAt,omitempty"`
	PurchaseId         openapi_types.UUID  `json:"purchaseId"`
	Reference          string              `json:"reference"`
	ShippedAt          *time.Time          `json:"shippedAt,omitempty"`
	Status             SellerOrderStatus   `json:"status"`
	StoreId            openapi_types.UUID  `json:"storeId"`
	StoreName          string              `json:"storeName"`
	SubtotalMinor      int64               `json:"subtotalMinor"`
	UpdatedAt          time.Time           `json:"updatedAt"`
}

// SellerOrderCurrency defines model for SellerOrder.Currency.
type SellerOrderCurrency string

// SellerOrderStatus defines model for SellerOrderStatus.
type SellerOrderStatus string

// Session defines model for Session.
type Session struct {
	AccessToken string           `json:"accessToken"`
	ExpiresIn   int              `json:"expiresIn"`
	TokenType   SessionTokenType `json:"tokenType"`
	User        User             `json:"user"`
}

// SessionTokenType defines model for Session.TokenType.
type SessionTokenType string

// Store defines model for Store.
type Store struct {
	CreatedAt      time.Time          `json:"createdAt"`
	Description    string             `json:"description"`
	Id             openapi_types.UUID `json:"id"`
	ModerationNote string             `json:"moderationNote"`
	Name           string             `json:"name"`
	SellerId       openapi_types.UUID `json:"sellerId"`
	Slug           string             `json:"slug"`
	Status         ModerationStatus   `json:"status"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// StoreInput defines model for StoreInput.
type StoreInput struct {
	Description string `json:"description"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// StoreProfile defines model for StoreProfile.
type StoreProfile struct {
	CreatedAt         time.Time          `json:"createdAt"`
	Description       string             `json:"description"`
	Id                openapi_types.UUID `json:"id"`
	Name              string             `json:"name"`
	SellerDisplayName string             `json:"sellerDisplayName"`
	Slug              string             `json:"slug"`
}

// User defines model for User.
type User struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// UserStatusInput defines model for UserStatusInput.
type UserStatusInput struct {
	Reason string     `json:"reason"`
	Status UserStatus `json:"status"`
}

// Variant defines model for Variant.
type Variant struct {
	Active     bool               `json:"active"`
	Attributes map[string]string  `json:"attributes"`
	Currency   VariantCurrency    `json:"currency"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	PriceMinor int64              `json:"priceMinor"`
	Sku        string             `json:"sku"`
	Stock      int                `json:"stock"`
}

// VariantCurrency defines model for Variant.Currency.
type VariantCurrency string

// VariantInput defines model for VariantInput.
type VariantInput struct {
	Attributes map[string]string    `json:"attributes"`
	Currency   VariantInputCurrency `json:"currency"`
	Name       string               `json:"name"`
	PriceMinor int64                `json:"priceMinor"`
	Sku        string               `json:"sku"`
	Stock      int                  `json:"stock"`
}

// VariantInputCurrency defines model for VariantInput.Currency.
type VariantInputCurrency string

// CategoryFilter defines model for CategoryFilter.
type CategoryFilter = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ImageId defines model for ImageId.
type ImageId = openapi_types.UUID

// InStock defines model for InStock.
type InStock = bool

// MaxPrice defines model for MaxPrice.
type MaxPrice = int64

// MinPrice defines model for MinPrice.
type MinPrice = int64

// OrderId defines model for OrderId.
type OrderId = openapi_types.UUID

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// ProductSlug defines model for ProductSlug.
type ProductSlug = string

// PurchaseId defines model for PurchaseId.
type PurchaseId = openapi_types.UUID

// Search defines model for Search.
type Search = string

// StoreFilter defines model for StoreFilter.
type StoreFilter = string

// StoreId defines model for StoreId.
type StoreId = openapi_types.UUID

// StoreSlug defines model for StoreSlug.
type StoreSlug = string

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// VariantId defines model for VariantId.
type VariantId = openapi_types.UUID

// Problem400 defines model for BadRequest.
type Problem400 = Problem

// Problem409 defines model for Conflict.
type Problem409 = Problem

// Problem403 defines model for Forbidden.
type Problem403 = Problem

// Problem404 defines model for NotFound.
type Problem404 = Problem

// Problem401 defines model for Problem401.
type Problem401 = Problem

// Problem429 defines model for Problem429.
type Problem429 = Problem

// Problem503 defines model for Problem503.
type Problem503 = Health

// Problem503JSON defines model for Problem503JSON.
type Problem503JSON = Problem

// ListCatalogProductsParams defines parameters for ListCatalogProducts.
type ListCatalogProductsParams struct {
	Q        *Search         `form:"q,omitempty" json:"q,omitempty"`
	Category *CategoryFilter `form:"category,omitempty" json:"category,omitempty"`
	Store    *StoreFilter    `form:"store,omitempty" json:"store,omitempty"`
	MinPrice *MinPrice       `form:"minPrice,omitempty" json:"minPrice,omitempty"`
	MaxPrice *MaxPrice       `form:"maxPrice,omitempty" json:"maxPrice,omitempty"`
	InStock  *InStock        `form:"inStock,omitempty" json:"inStock,omitempty"`
	Page     *Page           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CheckoutParams defines parameters for Checkout.
type CheckoutParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ReceivePaymentWebhookParams defines parameters for ReceivePaymentWebhook.
type ReceivePaymentWebhookParams struct {
	XCartlabsSignature string `json:"X-Cartlabs-Signature"`
}

// UpdateAdminProductStatusJSONRequestBody defines body for UpdateAdminProductStatus for application/json ContentType.
type UpdateAdminProductStatusJSONRequestBody = ProductStatusInput

// ModerateStoreJSONRequestBody defines body for ModerateStore for application/json ContentType.
type ModerateStoreJSONRequestBody = ModerationInput

// UpdateAdminUserStatusJSONRequestBody defines body for UpdateAdminUserStatus for application/json ContentType.
type UpdateAdminUserStatusJSONRequestBody = UserStatusInput

// DemoLoginJSONRequestBody defines body for DemoLogin for application/json ContentType.
type DemoLoginJSONRequestBody = DemoLoginRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetCartItemJSONRequestBody defines body for SetCartItem for application/json ContentType.
type SetCartItemJSONRequestBody = CartItemInput

// ReceivePaymentWebhookJSONRequestBody defines body for ReceivePaymentWebhook for application/json ContentType.
type ReceivePaymentWebhookJSONRequestBody = PaymentWebhookEvent

// CancelPurchaseJSONRequestBody defines body for CancelPurchase for application/json ContentType.
type CancelPurchaseJSONRequestBody = CancellationInput

// CompleteDemoPaymentJSONRequestBody defines body for CompleteDemoPayment for application/json ContentType.
type CompleteDemoPaymentJSONRequestBody = PaymentCompletionInput

// CreateReviewJSONRequestBody defines body for CreateReview for application/json ContentType.
type CreateReviewJSONRequestBody = ReviewInput

// UpdateSellerOrderStatusJSONRequestBody defines body for UpdateSellerOrderStatus for application/json ContentType.
type UpdateSellerOrderStatusJSONRequestBody = FulfillmentInput

// CreateSellerProductJSONRequestBody defines body for CreateSellerProduct for application/json ContentType.
type CreateSellerProductJSONRequestBody = ProductInput

// UpdateSellerProductJSONRequestBody defines body for UpdateSellerProduct for application/json ContentType.
type UpdateSellerProductJSONRequestBody = ProductInput

// CreateProductImageJSONRequestBody defines body for CreateProductImage for application/json ContentType.
type CreateProductImageJSONRequestBody = ImageInput

// ReplaceProductImageJSONRequestBody defines body for ReplaceProductImage for application/json ContentType.
type ReplaceProductImageJSONRequestBody = ImageReplacementInput

// CreateProductVariantJSONRequestBody defines body for CreateProductVariant for application/json ContentType.
type CreateProductVariantJSONRequestBody = VariantInput

// UpdateSellerStoreJSONRequestBody defines body for UpdateSellerStore for application/json ContentType.
type UpdateSellerStoreJSONRequestBody = StoreInput

// CreateSellerStoreJSONRequestBody defines body for CreateSellerStore for application/json ContentType.
type CreateSellerStoreJSONRequestBody = StoreInput

// AdjustVariantInventoryJSONRequestBody defines body for AdjustVariantInventory for application/json ContentType.
type AdjustVariantInventoryJSONRequestBody = InventoryAdjustment

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D17c+O2nV8Fw+sfbSpZsuPNZZ256XjtpHGb3fgsb3tzm20GIiEJMUlwAVC7iqvvfoMXCZLgUw97d67T",
	"SWIRxOP3fuHHR88nUUJiFHPmXTx6CaQwQhxR+dcV5GhJ6OYHHHJExS849i68DymiG2/kxTBC3oXn61He",
	"yGP+CkVQDOSbRDxjnOJ46W23I+8mQFFCOIr9zd/RJptshWCAaD6bNWwsxo08ij6kmKLAu+A0RfYiEfz0",
	"E4qXfOVdnJ59O/IiHJu/vx25thDBJboJsrUTyFf5ylg/bVpxQWgEuXfhpSkWIx1rxDNO/Ic6YGH92AGr",
	"OSEhgrGc5TX8dEuxj+qmicxz5+ZwzL859yQ8cJRG3sU02ymOOVoiqhbBcfMi5vkui/xMA0RrYU70091g",
	"fguXtYdIxDN7ugAtYBpy7+LU2vupc+9i3hn+vXFu+dw5/9l0JPCkF5hO25ejJEh9XgusJHu+I7jUPLMw",
	"XdasxMSjpkUck6bUX0FWz15JPmC37c8QpP6qDicfvDoJMZ06Z+OEomYBx8SQwrQJ5BxRMfRf7+D49+n4",
	"5fs///EvF+Psjz999QevdrVaEDH9dEf4iFl2Qe7g071lDayesj1w+j8gxTCuZ5F19nyXdbbiZZaQmCGp",
	"B1/B4A59SBHj4q8/ULTwLrz/mOSqc5INn9xSMg9RdD6detuRd0XiRYj9Pu+9FO/9QOgcBwGKe7z4tXjx",
	"DeE/kDQOerx37imZYLZ9IYyCmKNY7homSYh9yDGJJ4ka9OffGJEbyyHqWko9zRZScA0Q8ylOxHRC2cdr",
	"GOIAUA1deyOnT7ERn6IAxRzDkAFCAUOMiQH2vr4+7r5YulhgH6OYgwTRCFc3dH7MDd0hRlLqIxATDhaS",
	"0uy9vDzmXmYccgR8w2LWPs6Ouo/LlK8E0aj5gZCeUcIZQJ98hAIkJIyycqUwuUOcbsaXC61wKjo1twi2",
	"+YleNJJdv5P8iGDIV66DXKMExYEwvUEawzXEIZyHyCts42+zn988IXBDHGGOaHl/M0TX2EdvrV+7CsAX",
	"SnBWZzCb6jGRBM525N0T8hrGG600WHdhfCal/9sYpnxFKP4d9RHkp1JFapiK9y6DCMc/r8XJ0Eep2SlJ",
	"EOVYqTXoc7xGMxSGiEoznfU28EcC+ZSsUSCtjiET+CmlguTEqygWw955N9d33vuKXhakEeI1oigYvN0l",
	"JYy9RsIUjQPM0GscEzpgniSdh5itUKCNaTZoDmURD3lXWFNsiD+WW0Xv9CQVHLpOZ+925KKcKnLqgG2h",
	"PMcxmf+GlAyXRKvXlVQaBFiwPgxvLepdwJChUYmgs0hEi7gxcQ1JfhRBjoJLXgBmADkacxwhz0mFloB6",
	"rD5H8YJQv3HOOA21lFK2ae0cr+Rhug6PUMzvENSy13J+Xjicn5GHgw7W8EgFRiSAMUcR6yDMpZsq3hKv",
	"6/kgpVBCXJnqDrgx7bNUH3DIU2YLiIxAhVuWMqm2AqfIYLnH1XpQOfZN7fZsv2qYjzTy0iToS27ap+mO",
	"AO0kVWFfYn8JhNznzM83smN6El0j4zXatJ8hxtpjRi0umiywRoHGbT60gVQrIISr2Vc6DOB0zJIQbmpJ",
	"AkUQh4Xp1C/DeY2SetPF4PeOKKMnZ4um0QJSMzVyCP25aMYc0gaP3rpFEz0wmgaYf7/W5mTVSKmRs9Dn",
	"hHZkbTm2Fo/y6Z0GvZEx83QjA9NMqjmh9QThiR82jKPIKW2G0BjksJ6SC/I+h1hXatLe2k2/4ffywWMX",
	"UsghNzKoKs1T2IU+rg0oF0FcwdhHYShN/ps4SfsaArRWB1opgrM2WtezuDdIHbTax5TFPVRSd9Ev9iWt",
	"OJfiZemcEw7DoTavfPm/UxhzzOUZW0zUfYiaDKQZKMrnKO+rTdgIEN1w5deVRI3x/LIMzv48F6kV39Ki",
	"skgpHlO0QGIWp2wIcYzud0FZYqcUWolNj64Vk0kxcVB5/sFFG6eufbGH1DlDGmMuc05DD7y2A8StB9aj",
	"aw5cokc7tmynYmyoFWFUXECd2iIFC2CjMvFVQFEhhhY3ypD5EPFZwKPJYL182ZrAsqGVzVG3OSWmKkyY",
	"ibnO8k4y81Zu7ka9c+qQfftzA3aSoiUolaxvTSfq6OWl3IDMPd4SHLudta8z5pLRtofg2uQ1ishPZIlj",
	"K4nSR5l3NonL+lv86NrQD2m4wGEoPJPdrIss1+t5o3Z32+HGUuIjxsTzkcdWOEmkR5tFUqQnJk0hp3db",
	"ISY5v+vEOuZboZLARHyNCnRCwUEelRWqhyMP8ihLCoMdd6/qNgZgCob8Hn3i5UzwNy7sJIRh42q0GDYt",
	"atyKDfxxxXnC/nIxmfx78u5fk/d/arV6UqkYzMZroXGHkhAq5/rQgOl93IvJhCL2yy8nfkjSAMeQbsQf",
	"JJr8e6KiA5O9wCEWHiOhm8vgt5TxyGQjukMhQKHyvWLCLcqdvt+60O50Ks5KTsVp27nUmqMm52IHWVkf",
	"kLD3/OLcRf+QsY+EFtVG9uOod7GVfWiziWw617FfkwDRwS5fTDjqFPSsCioT/pZYEbvpIa5GauHm88yq",
	"gh/FgZL63RaXiX280Fmwqhyfk2DjlNMDAhIdLYcHrKoMHFEE2Gs9jnnYNdwgFzWvjNSx24IJt3AjZMMV",
	"iZIQDSUvknKfRIX4EEv9LL+7gLiTijbTNOyziVgcS4489CnB7bZCNv8/0XxFyEMWbjtwBLUxuuXWTRFJ",
	"Yz7UAezllMsUdufgmFF57aRq5rXfGhUO1uK9deRBrgN1GaUoFJ/YdGJ+60qi+UrFEK7EpJNu8zx5L93L",
	"tapyQFqqvpugJRmUuaYvCr7p+dQdvaoRMzkUu8ZlSgDTsDIyqcGO1Zmx6+zon19u8/NNGQYULrid2xYc",
	"Sf0VXv9/FvEZZxG7Z5EKRHQ4d6gjBzwTd1JuruhLWXtrAuMAI8nguyOjlGRN0XKfNgSryjhqTOrkQmJw",
	"XbMNUOuMTVTdAFlzW2GXuKcp4U+jCCpZXxaZiV7FkROwbjXUJHmc5YglwtIxSn2/wroKoWZoAICycA+W",
	"1zu1Webkq19+mZ185XVyBHMdYKuJ7q5gg09fQlg1dThEvVum7k6KWuelHPZxlgkr31EaZbeD6g31KnEN",
	"0eMHVqZtAe1iZL5GuxVhUcha5he+MlA76UNX1zlc+3SDulY5DDD4DpCz1h7HjeVd1Y2ZdSphKXrGLb6Y",
	"rDdAdC0jJd9L35j1AQgr1cN2ksdWKWSHVFSnM2uCyA+9l/T90Jf3ksy3rRpD1pb5V6SJKh0VqwFcRQDm",
	"DycFlFDby7Q0d9ecdQMHYKEvolzgyy4HwOU6AEd9gNYa3asAdkz6l4RGNYb4q+YpyV3YCg/92juceIfM",
	"rYIeBpyJUxczKG0plFEvJSjH1hLl4QLiPZnHEildI5CQi/8qRL5GLZyVRb0K6Zt2gO9F3ucyPsdJ5eRF",
	"JtJnbAjxt8lqRZdDvIuhxPmsUVnCSwX4boDXA7bWg4FrRLXPmdMLSedyUucpc4kdp9Fch+9JqtISzXK9",
	"n7esRVVbJMucwOzCLOMERrdiYZfgtG1Fhx+YV77mNzmqUsyI5l6m/mG9g6xq5QCytWd0xDbX2szxvAan",
	"z76TQruDnZJHWeVPLy+lkxNhkZrlRzyTUrg9KZlSX4ncPHbX1uXXE+p9CRPbcjBjH01UhX4ng2y3mjCx",
	"rLoj7rhKISa+Jw+o5t6acpVu4naDnYtJ7kvZx1cIUkSde0r1dZ22iypVmWzt2V7W3q2e3okCU2R64Cx3",
	"bST7dLrLzbsoKyF5o8tbOsXEpx1i4pI2u0qBHdNV3YRVpV5mXxIiO2vHNFQJ6r1YXsqcAbZnbwoaivd9",
	"Bkv7pT8kbG4pWeDwM2bJnfjtuuU+ITtwKLtE8JU9tZVSmVuXJdp9xrcke15frDt0VX+rK/CthQP5y88o",
	"39X1uuiAPJepGuiZf1fAdOaZIOcUz1O+a4H6AaK0LlnQIbaS7BLR1KFSa8lvztulT5cLbU7VKWOVWohY",
	"mCgconxLT2a7NEobaGRQ3foTEMMXjeWhCK7iVSo5P6WYb2ZClujWadInuEzV5ZO5/OsHA4u//fPetNWT",
	"TK/8h2zmFeeJCjwtKGKrK0IeMKoYSya1jkkMZmIDCPhyJPiI+QrcQr76r8kJ+In4MAQ/3t/fgpQhBnxI",
	"eQjn7FeqZgfMJwkKACcAFlsOUSIgciJzud6FpybPW879+uuPhPFxeb78GDDBf0cb1dsIxwviOEE6D7EP",
	"7r6f3QOfxJxCn4MFoeBKTwo+ojmAcQAub2+A1W5J7krHBb1s8OXtjTfy1ogqN9CbnpyfyG50JEExTLB3",
	"4X19Mj35WtUWrSSeJjJeNYFpgPkYrU0/2CWSHCqYS1XmB96F9xNmPL+yrxSC1S3vrLGHXLUx1C51MFbn",
	"gNY6tZpYnqvlVIA5UEAAMfqIGAcLTFV/Ot0ArrklU96+T7KFCZlKyGUz5pfQJGo5TRkH0Fpb4BYumdi8",
	"7HmBGVdY8N6LaTXKiNXfyYmuvyJebAS1I74a8VFYyAHb15A+IC7vLoFs57uC9a+Ig8ieWJ0/XgIZ1ukI",
	"yMTq5FRP91Z3oqelfLtN0v5o/3vVkwXOQwRCzAQQmRKkIeSCbJW5KySLFFXoE3fReFY9JUk7M5GBgbGU",
	"blaDmDKGnIiZPGaZou0kt2YTyFU72CK23kpH3QaTVViQd7l+5wZzPmSSt+Xdvs+K01/pXNFeuMZRF7ct",
	"opDTFG0PzbcZNVXJQgEzMCizyUNx77Sde60uqgMYXrxx3v5G1v9UvvCy/YWsQ2uRimeKZAGhgCIcM9lq",
	"UpNfdvImos0bdzTLkqzn2pNJkpp+IYNFiDoRgB8hljKYULCCa/Ffa0TzO2wOqaFgJmVDYWg7nCePOtq/",
	"neTRuwbhoGONaKZbO/eTCKaL86HkQfkm5JGFgSaIKmb/IZGCNFeoy4oKaQP4s4B+OfMmnxeYntv1iM86",
	"IDbz11vd43AnaPXwUAdocZX42J/5KuYcM7hAwtOhUlrtx3KVIC9axK0Ymjyqxt/9NLYVherLnLoJeX/e",
	"RJ9glKi4oom7eXcokfHQgnmZkBD7G7DGRKUGWZ48uLDCgdtRR34rxwifQvfr5Fut4k81jX7hml5GrYSq",
	"l+etIe6UryYBisg4JEustAxhDhmU9T3xDqMmKn1Vjq0nTHf0xq7NwgdgIBDMqVwv7AMBPQB9U2Zjdcee",
	"IT7OAz31H5zYDiOssw50Um7evB15L7qsVN9B2o6NeRfv3tvkZ0NKASoiQLdSNNR3I3vS841NgC20d0i6",
	"+xxo7jtg4no6GMjQTpQ2QOqdtr9SaPT9GdCnDATI9Jn0663uIC2kSlSkv5ZWxfMK1ZxXI6U6FAwWMMLh",
	"BlC0Jg8oKB/gsRwyfvd+WzjUnXwvIxE1W8spTFy39hh6TUOhT8ME+hGgRHiswS4k35t++yJBbjFDAsvg",
	"VoMFX/fcrAtyyp6cB4S6nN8B8iuZG+Eyo6BDZXiNgMyfqPCXzJjsI8gpq0zVQktK0gQFYL4BWc2pAZzc",
	"aQ60ifQdJo/ZBYWtbn6EVE1RmYwjskZZY72+5nf+hR5lgR8ZGcZelcSyo1OqIKHAjRUsShAeeTqFWQTh",
	"TBHjXuC3f/Vd7Ax5ZP3dHW8DNO4RvYbLQHsMyiXMaARYl3mc7MhhSJbdcg1XarD9DYZ+YSr1obTtqHVk",
	"6UOPHd6wP5vWYXj2qcEuY823DTuMNV9b7DD0VvUW6TRO3mQ/qPyyewE42OE2y5/kGRNKIh0WNVE3NohT",
	"Gow9RTEqe+NnSxdIWZJkDTVPHlmYLrfNStqm6aG5GHkD+xj40a16umAIqI5GLjwNVEQ1SBKGQBFDeum+",
	"eJpQeS+mWQhpQNzpoc8WYcXbSc4vl4kBQMNRGmY6kmnAsFcsyYBpRgZZ9f7YXFfIVs2RZmBcRFqW4OjI",
	"WjukNHbBkhU9tap1vbPp2Tfj6bfj07P70+nFVPz/f70yan6EcRDBAIElIYGWdKGs14ngA6Kq9kaccnr6",
	"8tuXi+l0PJ1Op+P/FP/4dqr/VP87neaVOW9SBmMOKQRXFC6kHHOU4XozSLEpkb3wYvPS2FcvdQ7jFuqb",
	"XfEJ3enRMK9ErGBh9cIxbJ4WqZKRq3OHDdJFGA8YtVozZtgTJjvt/il7yrdYB2sVCJqpgW8DowasK+Q/",
	"lOImZYmWMhwvAYMRAqXvZgOKeEpjBgjFSxzDEGSCR7ioJBVijyEq87L8I/aRYLIi1q7MDvoKk9Knvh0S",
	"5XR/ito0TnHqaH1kFaySF62Aas4ItJAazHe9XIf9ROgsx1RgDgFsOiDLA6oT6WgAIKbLhcMLWclu4JNQ",
	"11zXKZSf8BrFiLFDBlXqP0Z5q+7BASi32cRZkk6Bvjcngy961+boepHC4SmCyqeuO/0dggF+uuNfW53Z",
	"gdrscDLqAL4g//YntU7uBGHUSDY6HvZWZdAOBrq6jKUJx+UZy0GBzIJi9O05awOUsdWiuVkXvimMfEJ1",
	"WOgqvT+VWDjfAUpog5TKEjRZ3xCXgGmwUwSyQpFWAmzyUXVBborm+wivUbFpclUTypJwFWLPDc//GZta",
	"7PEML2PIU4p6fU7/UHWGjg7QneJ/jkyMfBtA30cJVxVBMJRiygjiHXTrkMzZ3gxhjXjA8DJGAYiI0C3a",
	"dpB12RaJaYBm1GV/0LXeo7Y+pPpkjJ+bTXtj+lcyOZHB4ABsPy+uYCMi+62Eiclj3h+g0XvOANI7wpH3",
	"HzhsRKqLoSvTTwULUJqGOIpSLiWmjFGzGCZsRTjbNUOS56SSHHz9cDJRzQzqBbH6FuD+0HOIhEr5a4VH",
	"Tqo0kcaV6RVRdACF9ye8+yB3Ir7M8i51/vzwc7QgFBVu38zREsf9pYkwJuqd82sUkTGJww1AcZAQHPPv",
	"hGZc4wBRwFAcMKNhtClidmZO5PDH1RcskJj61mob8szYoeZ7G8+IJ/K4wIIjmiGAUxjrxthfCivsOfBg",
	"KLBgFdXbQ1Z+oUa2y5CFbs91GGq028F1IsHTPS/dVEhfzgYcke6GS1SdSJGWhAzVZ8mNguVRm9hQgyYk",
	"67BbaynPiv1an+6GTLG7777uyVjAKptku1rK2vabo5DES3UR0iCnfLOirOwK6Jk8yn/3KN+vNr3qq6J+",
	"ViseTD9Vvv549BJWi5rqK2EKvPRFmmaXwVoYZ4BQoJwAQD7G9VLEwluRVDsV0yioP4ebu6XSgr3JE3M2",
	"DcWsMNDUIDju26nnjjoPBS1V4daguQtA9Q56OfZJNHhrFcg1hQtuAHgkLi1aZIWkT5JhooJIB7/Y96mb",
	"QiNlLO92ffqpCnYy21Wxx3FxtnuYxS9uvx3hoy56el9IfQ5sf0RaMjo62Av7DycMtY/duX+iP4RW76ld",
	"qgFfhijQhykJgWNaPmoDVpuMHXCXf2uvSVUXvo72/Njd+sT30+h4/e3BWrMKYPNxws+hND0pbHowUU0e",
	"5b9bboxcy9/3RWAdir7VnlxC5Ly2PZgCBVBnCD4HPCqwFs0VfQpZ7kOiBPocUBRBHAsf33zWr86QT51p",
	"bnmB4amQdyBBUvk6/tMYELUyRe+vzKfHNyD0RpxEZuoE/RVUMaTss5ED5InWdPVaStfTfxkGRuVywK6y",
	"QE+YewHK8iQUwJItA3AUoQBDjgo3Wjsjyv5ObAd7wvR7fX4WRaHL6JFtiuzbufXmxDr/vO6ReV6HDJLS",
	"RppphZlG+s1BAnP54Pi9iWaFWNfu/nZNtFy36+roXufg2D99W63mn0t/qCx0LQZ8ByLIEcUwVBpElrHy",
	"lMaAE6C/fvHkLnMTelvjns8Ju6dH4DB5G4Sl8whzgeVKm7ajlNI3RD9rkWnJMaPe7Nvwk7wEpj67dRn8",
	"ljKeKRXzwvO73p3tTe046lzkOT2G+jMioqD+dvF1xRnNbFYtk0ublftT2L2pdXMKRNcGkfKz7N4EJniy",
	"PpXY0jNWruGkMccRAupiwUleBmyK+0eP9Z1qMIlVjwjV/YJZr2fV5dUJbGUHIhjDpfR1rJdn5n5wTa9p",
	"u5+ZvpRkvW1uItWtPFb+grnN5N6Bgnt1CrsFsC0/JBysnrDWXKr9VnWqV3k/DOkS6wtLhZPIfgKPTTeD",
	"mD6TTMTLSgVrgjw97jiJXRvsZ/VOatJCcVdhRlMkU53wurau3Xq/WNe+fb/9vwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
