// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package contract

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CartCurrency.
const (
	CartCurrencyIDR CartCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartCurrency enum.
func (e CartCurrency) Valid() bool {
	switch e {
	case CartCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for CartItemCurrency.
const (
	CartItemCurrencyIDR CartItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the CartItemCurrency enum.
func (e CartItemCurrency) Valid() bool {
	switch e {
	case CartItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for ModerationInputStatus.
const (
	ModerationInputStatusApproved ModerationInputStatus = "approved"
	ModerationInputStatusRejected ModerationInputStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationInputStatus enum.
func (e ModerationInputStatus) Valid() bool {
	switch e {
	case ModerationInputStatusApproved:
		return true
	case ModerationInputStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ModerationStatus.
const (
	ModerationStatusApproved ModerationStatus = "approved"
	ModerationStatusPending  ModerationStatus = "pending"
	ModerationStatusRejected ModerationStatus = "rejected"
)

// Valid indicates whether the value is a known member of the ModerationStatus enum.
func (e ModerationStatus) Valid() bool {
	switch e {
	case ModerationStatusApproved:
		return true
	case ModerationStatusPending:
		return true
	case ModerationStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for PaymentCompletionInputOutcome.
const (
	PaymentCompletionInputOutcomeFailed    PaymentCompletionInputOutcome = "failed"
	PaymentCompletionInputOutcomeSucceeded PaymentCompletionInputOutcome = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentCompletionInputOutcome enum.
func (e PaymentCompletionInputOutcome) Valid() bool {
	switch e {
	case PaymentCompletionInputOutcomeFailed:
		return true
	case PaymentCompletionInputOutcomeSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentStatus.
const (
	PaymentStatusExpired   PaymentStatus = "expired"
	PaymentStatusFailed    PaymentStatus = "failed"
	PaymentStatusPending   PaymentStatus = "pending"
	PaymentStatusSucceeded PaymentStatus = "succeeded"
)

// Valid indicates whether the value is a known member of the PaymentStatus enum.
func (e PaymentStatus) Valid() bool {
	switch e {
	case PaymentStatusExpired:
		return true
	case PaymentStatusFailed:
		return true
	case PaymentStatusPending:
		return true
	case PaymentStatusSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventDataCurrency.
const (
	PaymentWebhookEventDataCurrencyIDR PaymentWebhookEventDataCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventDataCurrency enum.
func (e PaymentWebhookEventDataCurrency) Valid() bool {
	switch e {
	case PaymentWebhookEventDataCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PaymentWebhookEventType.
const (
	PaymentWebhookEventTypePaymentFailed    PaymentWebhookEventType = "payment.failed"
	PaymentWebhookEventTypePaymentSucceeded PaymentWebhookEventType = "payment.succeeded"
)

// Valid indicates whether the value is a known member of the PaymentWebhookEventType enum.
func (e PaymentWebhookEventType) Valid() bool {
	switch e {
	case PaymentWebhookEventTypePaymentFailed:
		return true
	case PaymentWebhookEventTypePaymentSucceeded:
		return true
	default:
		return false
	}
}

// Defines values for ProductDetailStatus.
const (
	Archived  ProductDetailStatus = "archived"
	Draft     ProductDetailStatus = "draft"
	Published ProductDetailStatus = "published"
)

// Valid indicates whether the value is a known member of the ProductDetailStatus enum.
func (e ProductDetailStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseCurrency.
const (
	PurchaseCurrencyIDR PurchaseCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseCurrency enum.
func (e PurchaseCurrency) Valid() bool {
	switch e {
	case PurchaseCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseItemCurrency.
const (
	PurchaseItemCurrencyIDR PurchaseItemCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the PurchaseItemCurrency enum.
func (e PurchaseItemCurrency) Valid() bool {
	switch e {
	case PurchaseItemCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for PurchaseStatus.
const (
	PurchaseStatusExpired        PurchaseStatus = "expired"
	PurchaseStatusPaid           PurchaseStatus = "paid"
	PurchaseStatusPaymentFailed  PurchaseStatus = "payment_failed"
	PurchaseStatusPendingPayment PurchaseStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the PurchaseStatus enum.
func (e PurchaseStatus) Valid() bool {
	switch e {
	case PurchaseStatusExpired:
		return true
	case PurchaseStatusPaid:
		return true
	case PurchaseStatusPaymentFailed:
		return true
	case PurchaseStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	Admin  Role = "admin"
	Buyer  Role = "buyer"
	Seller Role = "seller"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case Admin:
		return true
	case Buyer:
		return true
	case Seller:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderCurrency.
const (
	SellerOrderCurrencyIDR SellerOrderCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the SellerOrderCurrency enum.
func (e SellerOrderCurrency) Valid() bool {
	switch e {
	case SellerOrderCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for SellerOrderStatus.
const (
	SellerOrderStatusCancelled      SellerOrderStatus = "cancelled"
	SellerOrderStatusPaid           SellerOrderStatus = "paid"
	SellerOrderStatusPendingPayment SellerOrderStatus = "pending_payment"
)

// Valid indicates whether the value is a known member of the SellerOrderStatus enum.
func (e SellerOrderStatus) Valid() bool {
	switch e {
	case SellerOrderStatusCancelled:
		return true
	case SellerOrderStatusPaid:
		return true
	case SellerOrderStatusPendingPayment:
		return true
	default:
		return false
	}
}

// Defines values for SessionTokenType.
const (
	Bearer SessionTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the SessionTokenType enum.
func (e SessionTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for VariantCurrency.
const (
	VariantCurrencyIDR VariantCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantCurrency enum.
func (e VariantCurrency) Valid() bool {
	switch e {
	case VariantCurrencyIDR:
		return true
	default:
		return false
	}
}

// Defines values for VariantInputCurrency.
const (
	VariantInputCurrencyIDR VariantInputCurrency = "IDR"
)

// Valid indicates whether the value is a known member of the VariantInputCurrency enum.
func (e VariantInputCurrency) Valid() bool {
	switch e {
	case VariantInputCurrencyIDR:
		return true
	default:
		return false
	}
}

// Cart defines model for Cart.
type Cart struct {
	Currency      CartCurrency       `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	Stores        []CartStore        `json:"stores"`
	SubtotalMinor int64              `json:"subtotalMinor"`
	TotalQuantity int                `json:"totalQuantity"`
	UpdatedAt     time.Time          `json:"updatedAt"`
}

// CartCurrency defines model for Cart.Currency.
type CartCurrency string

// CartItem defines model for CartItem.
type CartItem struct {
	AvailableStock int                `json:"availableStock"`
	Currency       CartItemCurrency   `json:"currency"`
	ImageUrl       string             `json:"imageUrl"`
	LineTotalMinor int64              `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID `json:"productId"`
	ProductName    string             `json:"productName"`
	ProductSlug    string             `json:"productSlug"`
	Quantity       int                `json:"quantity"`
	Sku            string             `json:"sku"`
	UnitPriceMinor int64              `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID `json:"variantId"`
	VariantName    string             `json:"variantName"`
}

// CartItemCurrency defines model for CartItem.Currency.
type CartItemCurrency string

// CartItemInput defines model for CartItemInput.
type CartItemInput struct {
	Quantity int `json:"quantity"`
}

// CartStore defines model for CartStore.
type CartStore struct {
	Items         []CartItem         `json:"items"`
	StoreId       openapi_types.UUID `json:"storeId"`
	StoreName     string             `json:"storeName"`
	SubtotalMinor int64              `json:"subtotalMinor"`
}

// Category defines model for Category.
type Category struct {
	Id   openapi_types.UUID `json:"id"`
	Name string             `json:"name"`
	Slug string             `json:"slug"`
}

// DemoLoginRequest defines model for DemoLoginRequest.
type DemoLoginRequest struct {
	Role Role `json:"role"`
}

// Health defines model for Health.
type Health struct {
	Dependencies *map[string]string `json:"dependencies,omitempty"`
	Status       HealthStatus       `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ImageInput defines model for ImageInput.
type ImageInput struct {
	AltText  string `json:"altText"`
	Position int    `json:"position"`
	Url      string `json:"url"`
}

// InventoryAdjustment defines model for InventoryAdjustment.
type InventoryAdjustment struct {
	Delta  int    `json:"delta"`
	Reason string `json:"reason"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ModerationInput defines model for ModerationInput.
type ModerationInput struct {
	Note   string                `json:"note"`
	Status ModerationInputStatus `json:"status"`
}

// ModerationInputStatus defines model for ModerationInput.Status.
type ModerationInputStatus string

// ModerationStatus defines model for ModerationStatus.
type ModerationStatus string

// Notification defines model for Notification.
type Notification struct {
	Body      string             `json:"body"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Kind      string             `json:"kind"`
	ReadAt    *time.Time         `json:"readAt,omitempty"`
	Title     string             `json:"title"`
}

// PaymentCompletionInput defines model for PaymentCompletionInput.
type PaymentCompletionInput struct {
	Outcome PaymentCompletionInputOutcome `json:"outcome"`
}

// PaymentCompletionInputOutcome defines model for PaymentCompletionInput.Outcome.
type PaymentCompletionInputOutcome string

// PaymentStatus defines model for PaymentStatus.
type PaymentStatus string

// PaymentWebhookEvent defines model for PaymentWebhookEvent.
type PaymentWebhookEvent struct {
	CreatedAt time.Time `json:"createdAt"`
	Data      struct {
		AmountMinor int64                           `json:"amountMinor"`
		Currency    PaymentWebhookEventDataCurrency `json:"currency"`
		IntentId    openapi_types.UUID              `json:"intentId"`
		Reference   string                          `json:"reference"`
	} `json:"data"`
	Id   openapi_types.UUID      `json:"id"`
	Type PaymentWebhookEventType `json:"type"`
}

// PaymentWebhookEventDataCurrency defines model for PaymentWebhookEvent.Data.Currency.
type PaymentWebhookEventDataCurrency string

// PaymentWebhookEventType defines model for PaymentWebhookEvent.Type.
type PaymentWebhookEventType string

// Problem defines model for Problem.
type Problem struct {
	Detail    *string `json:"detail,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Status    int     `json:"status"`
	Title     string  `json:"title"`
	Type      string  `json:"type"`
}

// ProductDetail defines model for ProductDetail.
type ProductDetail struct {
	Category         Category            `json:"category"`
	CreatedAt        time.Time           `json:"createdAt"`
	Description      string              `json:"description"`
	Id               openapi_types.UUID  `json:"id"`
	Images           []ProductImage      `json:"images"`
	ModerationNote   string              `json:"moderationNote"`
	ModerationStatus ModerationStatus    `json:"moderationStatus"`
	Name             string              `json:"name"`
	Slug             string              `json:"slug"`
	Status           ProductDetailStatus `json:"status"`
	StoreId          openapi_types.UUID  `json:"storeId"`
	StoreName        *string             `json:"storeName,omitempty"`
	UpdatedAt        time.Time           `json:"updatedAt"`
	Variants         []Variant           `json:"variants"`
}

// ProductDetailStatus defines model for ProductDetail.Status.
type ProductDetailStatus string

// ProductImage defines model for ProductImage.
type ProductImage struct {
	AltText  string             `json:"altText"`
	Id       openapi_types.UUID `json:"id"`
	Position int                `json:"position"`
	Url      string             `json:"url"`
}

// ProductInput defines model for ProductInput.
type ProductInput struct {
	CategoryId  openapi_types.UUID `json:"categoryId"`
	Description string             `json:"description"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
}

// ProductPage defines model for ProductPage.
type ProductPage struct {
	Items    []ProductSummary `json:"items"`
	Page     int              `json:"page"`
	PageSize int              `json:"pageSize"`
	Total    int              `json:"total"`
}

// ProductSummary defines model for ProductSummary.
type ProductSummary struct {
	Category      Category           `json:"category"`
	Currency      string             `json:"currency"`
	Id            openapi_types.UUID `json:"id"`
	ImageUrl      string             `json:"imageUrl"`
	InStock       bool               `json:"inStock"`
	MinPriceMinor int64              `json:"minPriceMinor"`
	Name          string             `json:"name"`
	Slug          string             `json:"slug"`
	StoreName     string             `json:"storeName"`
}

// Purchase defines model for Purchase.
type Purchase struct {
	BuyerId              openapi_types.UUID `json:"buyerId"`
	CreatedAt            time.Time          `json:"createdAt"`
	Currency             PurchaseCurrency   `json:"currency"`
	Id                   openapi_types.UUID `json:"id"`
	PaymentIntentId      string             `json:"paymentIntentId"`
	PaymentStatus        PaymentStatus      `json:"paymentStatus"`
	Reference            string             `json:"reference"`
	ReservationExpiresAt time.Time          `json:"reservationExpiresAt"`
	SellerOrders         []SellerOrder      `json:"sellerOrders"`
	Status               PurchaseStatus     `json:"status"`
	SubtotalMinor        int64              `json:"subtotalMinor"`
	TotalMinor           int64              `json:"totalMinor"`
	UpdatedAt            time.Time          `json:"updatedAt"`
}

// PurchaseCurrency defines model for Purchase.Currency.
type PurchaseCurrency string

// PurchaseItem defines model for PurchaseItem.
type PurchaseItem struct {
	Currency       PurchaseItemCurrency `json:"currency"`
	Id             openapi_types.UUID   `json:"id"`
	ImageUrl       string               `json:"imageUrl"`
	LineTotalMinor int64                `json:"lineTotalMinor"`
	ProductId      openapi_types.UUID   `json:"productId"`
	ProductName    string               `json:"productName"`
	Quantity       int                  `json:"quantity"`
	Sku            string               `json:"sku"`
	UnitPriceMinor int64                `json:"unitPriceMinor"`
	VariantId      openapi_types.UUID   `json:"variantId"`
	VariantName    string               `json:"variantName"`
}

// PurchaseItemCurrency defines model for PurchaseItem.Currency.
type PurchaseItemCurrency string

// PurchaseStatus defines model for PurchaseStatus.
type PurchaseStatus string

// Role defines model for Role.
type Role string

// SellerOrder defines model for SellerOrder.
type SellerOrder struct {
	CreatedAt     time.Time           `json:"createdAt"`
	Currency      SellerOrderCurrency `json:"currency"`
	Id            openapi_types.UUID  `json:"id"`
	Items         []PurchaseItem      `json:"items"`
	PurchaseId    openapi_types.UUID  `json:"purchaseId"`
	Reference     string              `json:"reference"`
	Status        SellerOrderStatus   `json:"status"`
	StoreId       openapi_types.UUID  `json:"storeId"`
	StoreName     string              `json:"storeName"`
	SubtotalMinor int64               `json:"subtotalMinor"`
	UpdatedAt     time.Time           `json:"updatedAt"`
}

// SellerOrderCurrency defines model for SellerOrder.Currency.
type SellerOrderCurrency string

// SellerOrderStatus defines model for SellerOrderStatus.
type SellerOrderStatus string

// Session defines model for Session.
type Session struct {
	AccessToken string           `json:"accessToken"`
	ExpiresIn   int              `json:"expiresIn"`
	TokenType   SessionTokenType `json:"tokenType"`
	User        User             `json:"user"`
}

// SessionTokenType defines model for Session.TokenType.
type SessionTokenType string

// Store defines model for Store.
type Store struct {
	CreatedAt      time.Time          `json:"createdAt"`
	Description    string             `json:"description"`
	Id             openapi_types.UUID `json:"id"`
	ModerationNote string             `json:"moderationNote"`
	Name           string             `json:"name"`
	SellerId       openapi_types.UUID `json:"sellerId"`
	Slug           string             `json:"slug"`
	Status         ModerationStatus   `json:"status"`
	UpdatedAt      time.Time          `json:"updatedAt"`
}

// StoreInput defines model for StoreInput.
type StoreInput struct {
	Description string `json:"description"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

// User defines model for User.
type User struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Role        Role                `json:"role"`
}

// Variant defines model for Variant.
type Variant struct {
	Active     bool               `json:"active"`
	Attributes map[string]string  `json:"attributes"`
	Currency   VariantCurrency    `json:"currency"`
	Id         openapi_types.UUID `json:"id"`
	Name       string             `json:"name"`
	PriceMinor int64              `json:"priceMinor"`
	Sku        string             `json:"sku"`
	Stock      int                `json:"stock"`
}

// VariantCurrency defines model for Variant.Currency.
type VariantCurrency string

// VariantInput defines model for VariantInput.
type VariantInput struct {
	Attributes map[string]string    `json:"attributes"`
	Currency   VariantInputCurrency `json:"currency"`
	Name       string               `json:"name"`
	PriceMinor int64                `json:"priceMinor"`
	Sku        string               `json:"sku"`
	Stock      int                  `json:"stock"`
}

// VariantInputCurrency defines model for VariantInput.Currency.
type VariantInputCurrency string

// CategoryFilter defines model for CategoryFilter.
type CategoryFilter = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// InStock defines model for InStock.
type InStock = bool

// MaxPrice defines model for MaxPrice.
type MaxPrice = int64

// MinPrice defines model for MinPrice.
type MinPrice = int64

// Page defines model for Page.
type Page = int

// PageSize defines model for PageSize.
type PageSize = int

// ProductId defines model for ProductId.
type ProductId = openapi_types.UUID

// ProductSlug defines model for ProductSlug.
type ProductSlug = string

// PurchaseId defines model for PurchaseId.
type PurchaseId = openapi_types.UUID

// Search defines model for Search.
type Search = string

// StoreId defines model for StoreId.
type StoreId = openapi_types.UUID

// VariantId defines model for VariantId.
type VariantId = openapi_types.UUID

// Problem400 defines model for BadRequest.
type Problem400 = Problem

// Problem409 defines model for Conflict.
type Problem409 = Problem

// Problem403 defines model for Forbidden.
type Problem403 = Problem

// Problem404 defines model for NotFound.
type Problem404 = Problem

// Problem401 defines model for Problem401.
type Problem401 = Problem

// Problem429 defines model for Problem429.
type Problem429 = Problem

// Problem503 defines model for Problem503.
type Problem503 = Health

// Problem503JSON defines model for Problem503JSON.
type Problem503JSON = Problem

// ListCatalogProductsParams defines parameters for ListCatalogProducts.
type ListCatalogProductsParams struct {
	Q        *Search         `form:"q,omitempty" json:"q,omitempty"`
	Category *CategoryFilter `form:"category,omitempty" json:"category,omitempty"`
	MinPrice *MinPrice       `form:"minPrice,omitempty" json:"minPrice,omitempty"`
	MaxPrice *MaxPrice       `form:"maxPrice,omitempty" json:"maxPrice,omitempty"`
	InStock  *InStock        `form:"inStock,omitempty" json:"inStock,omitempty"`
	Page     *Page           `form:"page,omitempty" json:"page,omitempty"`
	PageSize *PageSize       `form:"pageSize,omitempty" json:"pageSize,omitempty"`
}

// CheckoutParams defines parameters for Checkout.
type CheckoutParams struct {
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ReceivePaymentWebhookParams defines parameters for ReceivePaymentWebhook.
type ReceivePaymentWebhookParams struct {
	XCartlabsSignature string `json:"X-Cartlabs-Signature"`
}

// ModerateProductJSONRequestBody defines body for ModerateProduct for application/json ContentType.
type ModerateProductJSONRequestBody = ModerationInput

// ModerateStoreJSONRequestBody defines body for ModerateStore for application/json ContentType.
type ModerateStoreJSONRequestBody = ModerationInput

// DemoLoginJSONRequestBody defines body for DemoLogin for application/json ContentType.
type DemoLoginJSONRequestBody = DemoLoginRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetCartItemJSONRequestBody defines body for SetCartItem for application/json ContentType.
type SetCartItemJSONRequestBody = CartItemInput

// ReceivePaymentWebhookJSONRequestBody defines body for ReceivePaymentWebhook for application/json ContentType.
type ReceivePaymentWebhookJSONRequestBody = PaymentWebhookEvent

// CompleteDemoPaymentJSONRequestBody defines body for CompleteDemoPayment for application/json ContentType.
type CompleteDemoPaymentJSONRequestBody = PaymentCompletionInput

// CreateSellerProductJSONRequestBody defines body for CreateSellerProduct for application/json ContentType.
type CreateSellerProductJSONRequestBody = ProductInput

// UpdateSellerProductJSONRequestBody defines body for UpdateSellerProduct for application/json ContentType.
type UpdateSellerProductJSONRequestBody = ProductInput

// CreateProductImageJSONRequestBody defines body for CreateProductImage for application/json ContentType.
type CreateProductImageJSONRequestBody = ImageInput

// CreateProductVariantJSONRequestBody defines body for CreateProductVariant for application/json ContentType.
type CreateProductVariantJSONRequestBody = VariantInput

// UpdateSellerStoreJSONRequestBody defines body for UpdateSellerStore for application/json ContentType.
type UpdateSellerStoreJSONRequestBody = StoreInput

// CreateSellerStoreJSONRequestBody defines body for CreateSellerStore for application/json ContentType.
type CreateSellerStoreJSONRequestBody = StoreInput

// AdjustVariantInventoryJSONRequestBody defines body for AdjustVariantInventory for application/json ContentType.
type AdjustVariantInventoryJSONRequestBody = InventoryAdjustment

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5H1tc9s4kvBfQfHZD7vPypacl6kdT11tOcnMjneTjC9Obq8q5U1BZEvCmAQYAFSi8em/X+GNBEmQIiXZ",
	"zs59i0Wg0ej3bjSQuyhmWc4oUCmi87soxxxnIIHrv15iCUvGNz+RVAJXvxAanUefC+CbaBJRnEF0HsV2",
	"VDSJRLyCDKuBcpOrb0JyQpfRdjuJLhPIciaBxpt/wKYEtgKcAK+gecNO1LhJxOFzQTgk0bnkBfiLZPjr",
	"a6BLuYrOz578ZRJlhLq//zIJoUCvJYtvuzZC7OfAPuaMpYCphvIGf73iJIYuMJn77sNZMJ5hqReR3z2L",
	"NK4kK7LofFZiSqiEJXCzCKH9i7jvhyxyhZedC+Tqmw88gQUuUhmdn3lwzzrhXpPfemHr70H4T2YTRUO7",
	"wGy2eznOkiKWl0m5Xo7lyluu/N4nTCXxioKokW3xsetcp8WyYyWhPvUtEgBa8HiFBXRjXw04DP1rwDxe",
	"dfHkc9SlWbNZEJpkvBtpYb8ehvF/YU4w7Wbsuvx+yDpbNVnkjArQVu8FTt7B5wKEVH/9gcMiOo/+37Qy",
	"lNNy+PSKs3kK2bPZLNpOopeMLlISj5n3vZr3E+NzkiRAR0x8qia+ZfInVtBkxLxnkZFkh/a5cgFUAtVY",
	"4zxPSYwlYXSam0F//lUwjVhF0dBS5mu5kKFrAiLmJFfglGmna5ySBHFLXR+Rs8dAJOaQAJUEpwIxjgQI",
	"oQb4eD19WLxEsViQmACVKAeekTZCzx4SoXcgWMFjQJRJtNCS5uPy/UPici2xBBQ7FfPwePKgeFwUcqWE",
	"xsBHWErIcikQfI0BElAWxsQ02pi8A8k3JxcLGz+1PEHlx7bVjp73it24nfwMOJWr0EZeQQ40UYEWKihe",
	"Y5LieQpRDY2/X//y9hGJm5KMSOBN/K6Br0kMH7xfhxrA58ZwtiE4pEYA0sTZTqL3jL3BdGOdhhhujJ9o",
	"6/+B4kKuGCe/wRhDfqZdpKWpida5ZlDOWQ5cEuPN4oJzxWP1b6AqiPoYXb56F920HOEkIskAfzkxzl0D",
	"JxIysYvdCi8dLai5FhjmHG80rGIumcTpG0IZHx3DTiI9+T8LTCWReo/9w4s8wRKSC1lbSv12IkkGwSik",
	"iiw+RpogJUlLUjT30cTLX7giPJv/CsaSKRJdSiN9dfaV8llmLv0bHMXuDC/hA0/rTOfkhMMCFBQIcT8l",
	"FN4fwrLcD9d3Cpsd/VZHfHed311Q3vr+OSQbZyG8xG0RhFBQInWute+G134Yu3PDdnTHhhvy6EfAfprj",
	"U61Oo/oCZteeKHgEmzSFr0WKljB48tcn5pc0L4wvSRKiDD1OrzypX+BUwKShCDU+uuzw++93Joc+tUoY",
	"XcgZM9VSwtLMDbZ3Wpm3GrlLM+csYPuqFGqYze1UgsOsaINKVe5WLTqxW28uFSakrQe16Thsr7Rzm2El",
	"D9loaqVbzQgh+Qoy9potCfVSvRHSyFl3zOHk4J0a00ROTwwhZOO0Fs0SF6U5hxBEMkCs1gpCYlkI3zEw",
	"pdMJLDlWcevNLudnAYSwv1T2Yx+1xql8D19ls+bw3SzkCpggJk7c6eZ3OLVcRe1cBZz/+uNKylz89Xw6",
	"/Z/px39Nb/60MwYotJl0iHtoBQlD10Al45uL5NdCyMwF0cMplEAqdUhNmfSYN7vZhnbOAdtY3CPnE1tE",
	"K8m7a4tmzRJaaGMHKA9kmNT5Y36Z1HB+/iwkAliIL4zX7Uj542R0RdjftEOiBBfa9huWANfJyT7STpmE",
	"Bm+ez2ZBc9/UVZznnK3BlLoUNiM0dmIW7t/PdWtJZXgU1MnAxXU9iixs8tY2ZXOWbIKmKuYwLiofnKrc",
	"ElMca33ggEetJ4lMYaDv0Yu6KROzbX+TIT5c4Y2yDS9Zlqewr3ixQsbM+E7HQ1HEZVligUk6RGocmB48",
	"+4QlsOQkgq+5Bh+SGgvznzBfMXb743q8jdxDgBJsrOoYX5Wxgsp9s4BRmZmutgwMDSvHtls8HVx/1qS2",
	"sR0h/EC9Mz940mFYfOrLhvttqFhWK/nKZDkZlNWqpDPK30rrngKU1u7uMmxSKptd5ifPawnKs1m4hNFh",
	"WioqDk3OGwSztHJ2qCd8sydbr8qtN9TLi+j7Mx87bj+bXisF3u1t83UuOzxdc6eHalaoQpWVHvKt9d6t",
	"FbOAE+1bsuV090h6QjFCwvFCR6TFPCVipbUM83hF1h2W93gZ6OjCWlmHGM4pexzYZlLIUFRZrNef4GeF",
	"dXmbVLFSi5stGfBwL8WtbpP6y301kdNJUPrLIjr/2L99L8faTvZKrdt0amN34+G3RwjiiD1QqBoqX4+L",
	"Zz21gWay6AX6TybdSuQlfh/xyW+zk+9v/vzHv56flH/86f//YSfdvD32iVQP513jxSFlJteNUGQZNia3",
	"ablyu0qgBOs1aHTU1INnVA35sSUh2yridXUYCD0EcFgfx9V4kdVBTsPWwgPhWFl9b/YDTcpOnO64sE3h",
	"fYx9t/XdVf+qF/I8c1hHvXawUfVClZQJstM2pwSSvWIDfKAV2CNWuIdjLRuPXnqxd9eYYW6+nivtiNR1",
	"EwrwtfYyP+psSYwhiIA0Bf4LdwfPg2zIdTVpQLV60J6tQFSbPsoJ376Tj3Le50fcTqy9eKEuE205qh8Y",
	"hs4J3R9BCWiwdlSc4VrHgkeL96BCv4sTxd/3iSFpHhUGjhCtpxh+UHjguWDDaLSrSp+sTmntIl7x4NOg",
	"AtM7e1rjoGolLhVLJUlJRmhwqm8h2xr0TfitkWGjbxN22fy81px6UCVqqAPxCO75kG/kpPRIDqXR0luZ",
	"xvDRa+lpevyIi8WHO4c2oYfoXYxprCYmHdpiGhbbbSxxDEK8Z7cQLu0Y7RWXdLfRlQrI+0Z98QVgDjyI",
	"UyGM6vYJ3QcRSG98nP1lfWwt+CB9XS/BsOze9FN3ZPf3d0AyoLplrORg7du3AHYUzSpxDdZzbPFmqI7c",
	"lG3uexRCuisbZ8MrG7MHrmyMK2Z8ECGnmBCRp3jTaYG7T3/3leG9mzE0OLe6j/eku0/DFSEHK7a7xNCh",
	"2jiWZA3h0sKeRb2JAxoW6RpCI0/ApORkXshDW1HGREEhvXiyq59BIX5A/G0De2/J757t1sQhHZrNA3od",
	"VFu186hbw7/ZcRrfBjirDXVccCI310ry7F0W7RcvCtNZNNd//eRo8fd/vneXfrTgGR9aQl5JmevoGRYc",
	"xOolY7cEWqbNVfQIo+haIQAo1iPRFyJX6ArL1X9MT9FrFuMU/fz+/RUqBAgUYy5TPBefuIGORMxySJBk",
	"CNd7wDlTFDnVNanoPDLAqztAnz79zIQ8acKrtoFz8g/YmGZzQhcssINinpIYvfvx+j2KGZUcxxItGEcv",
	"LVD0BeYI0wRdXF0ir/9dY2WP76Jy8MXVpUqegJtQKJqdPj3V14NYDhTnJDqPnp7OTp+aPqSV5tNUZyBT",
	"m3/pn5agtVMpluk3SaLz6DUR8iLRdTs7snF56UnvlZ52n/4RKtD21HDnqYwGGRDc1iUAtzeEv2AiCV0i",
	"xtEKr9W/KmduRN7VkTVlkKOf5p43dBJJvBQKiwuT6am5DZpP78qseDv15hrfai7O1Zlhoxiw+Gp+Vtdn",
	"O9xCNWRa3Vvc3pSHyy9sk8xRLn80u5W2daZIXsD2QAEaISBtTjsKJo5zSorsHaf+axDlzbe6FDiAJbw+",
	"zlf3GPp17do1+T+apnVcn9hbw8yOxuuXodgY7TIzpnc2sx2pWWbfY/XKXU39nWqVFYY+bRJOXo6iS8Jy",
	"IcjlQq6mCWTsJGVLYnjKRECbyobr6H6Y0mrofmiuuMujvZfaIEFYoETJqYoShSQxUtRDOI5ZoQst3uXB",
	"a5AnVdjVfYt8qzn9dDenq4vGaoa5N9k/o3m3bTuJng9ZqfuCnR+pRucfb3yR8yllCJUxpFOxSvou9ZVd",
	"ufEFcIfs3afc/TvI3A/IRdk2NBdwkKTNdvPfu0Svp5ztnlK7B/lvIJ86v9HVA50beF3oO0SVmby7U1bV",
	"95bUPGvnLTYxQwuckXSDOKzZLSTNDdw1E7iPN9vapt7peaWIGGg7duGyrM5t2DWdhD6OEthPiDOp1OAQ",
	"kR8tv2OZoFEsmSBKunVwIbaXfYOR699A6svA90h1DT9A8pe6UiF1fm80JCVrFY6TGLSamPrFHg6rFpv8",
	"DSTSp3hmoSVnRQ4Jmm9QeabnCKcxrYg21VHy9K489tzaSzZgyt9NMc7YGsobfWMj0eoBExOLPjAzPpji",
	"tqbRodGgoYQhNzG0aFB4EtmCYp2E10YYj0K/47vv+pXUB/bfw/m2h8cdxWo1YYC3LR+4qcvGRZKoFJJD",
	"nuLYkxHktQgE1VHilC2HVb1emsFe3WtkUmheP9pOdo5svHo2YEb5WNeQse51sAFj3XtlA4Zeme71QeN0",
	"k+a9GiS/zTVU4HP96chdLCsrd3uJe0/EZtiOclPizSvpqeRRy1WHSE7vRFost/2e1hfMfYuA+m7+Q/Ck",
	"uxjXzRWUlCXePVxIB2eUC6+zxS3TwxylmAR2Wgo37BFLdn6D8pGqdt7G+girK3VWkFHsE6ODrCuIbxs5",
	"STPRKAShSyRwBqjxQCPiIAtOBWKcLAnFKXLdLTr8Y4VEpq1RAZBfSAyn0aTBtZcOg7HK03hTMqA/Z8fT",
	"H9fqHFQdu2WTCOqeGWQu2yHbbbC3Hx/llo+T/XpBn+IcIOJusesNmh3ZSBsx15ca8PAr/ajBNLUn3F0m",
	"9DVZAwUh7jNh6X4H64qzGIRAWKPZp1laTpW10uPTCmu3dbtIbfMcsIlXu3b/DnBCHm/7r7wHJpBBdn8x",
	"GkC+pHp2jHs7D5Iw6xUbm2vqNpR7JJ1tDutMdXUH2P5FgppDjH2Ynck/9a7Z9/vCt7WRj+gOay8DHM8l",
	"1vaHKHwBIdGCcGc8DygxaDeaFFyJteYHog1iOu7UiWxYZJ2AmH4xt9r7KmUxkDXUL8G3PWHwseT/PnFd",
	"ByfXZEmxLPRBzfD3Z+8pqw7d6B+UWweqnHo2wnEMucqJGUc41WbKGeIDfOs+VemjBcCW8UiQJYUEZUz5",
	"Fhs7wNp03ToRswQtpcvGG/3Kf1WOeswmkTJsOprSv9CFv5IG96D28/oKPiPK3xqcmN5VXd29+WJJkNGZ",
	"YtU1fr+J4pBAV5d2axGgDg1JlhVSW0xd/xEU52LFXFq/f/WxqvfmFfnG8USZ5O4U5xVk7ITRdIOAJjkj",
	"VP6g7MuaJMCRAJoIp6fWoKM5LBgH5FAPZDXmLRdQoK+8PvqDeH5vtrr58sxDtwoNyq4WEnjJAMkxtS9v",
	"7Wv/Rx+Z33NV9cjpm5PAmm/p9ipGnaesvEPa6Vmu6zcSH68vqn5/9VjdUZ5Za5qwQz2LtZVzSBld6pII",
	"c2a02WbTNGuWPYOq5WYL/yeaRNkX6p/8ud6nQPOa+R6oARtqmSOsYIz+Ulc8akS9p3aS2tMbg2zw2cNV",
	"iF9xvJD1Vs17N7p1g1arPLV7PEtGBvTF7+/taT00Z29NVn9rjb3jxeQBDxLc8WVyFHHZP2g0eBwuLdPq",
	"Rak+81B71efbExn/+aBHsSv2ha1OU46Ie4LrgeXkIqlOuojl3mgZsW9udQuJPV47rmV5tLNCSy5RzDMi",
	"lbI3esIP7CiwxCrZstDtBWsCX/bhjf/S2AANdlf8vj0drt8lfFgtLl9f65aGdfVA2wOrsA0M8gYi/bIi",
	"3A3trlKNmeQuITx8Q/91LaI9vILSkWjY+y06/N0dFFXkOL58+5fgv5FLFS6Y0UT7AWVYAic4RfEK06U+",
	"MZMFpyqNcy/gPnag08fendnNt8TdswfQMPVhhxe77zP7ngynk5WeFXPOzW9pnZYH9j2ZjnmRvnQpbsK3",
	"16MZekP/gc1Dj/NzBqLm/A7ppVR7dNCqzougL2s2mfvXvW2HOfC1Y6T+XxGiKc7JdH2muWUhtvp9CipJ",
	"Bsh0MJxW542ui2Byt+M/RaOJa2EXp7X/29UcY7cB+K4OZZjiJejHoavJVvbbU+317QzzW5CuA1U3OHmz",
	"XctT18onpozk2qbCGBi6t0G88ZaurIc309yYa098UbWw68Ya2wdVw5vL4J69hiNhd6DrlSpG9mleVRED",
	"ePtHjnF5AGCA1k47ahBd1bgN8FXncbk3v35cvr3Z/m8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
