global:
  environment: demo
  imageRegistry: ghcr.io/christolx
  imageTag: sha-0000000
  domain: cartlabs.christofletjhai.dev
  imagePullSecrets:
    - name: ghcr-pull

ingress:
  enabled: true
  externalHTTPS: true
  tls:
    enabled: false

backup:
  enabled: true

demoReset:
  enabled: true
  suspend: true

observability:
  enabled: true
  traceSampleRatio: "1"

syntheticTraffic:
  enabled: true
