// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/search/v1/search.proto

package searchv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	Truncated     bool                   `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsResponse) Reset() {
	*x = SearchProductsResponse{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsResponse) ProtoMessage() {}

func (x *SearchProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsResponse.ProtoReflect.Descriptor instead.
func (*SearchProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchProductsResponse) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *SearchProductsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type UpsertProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Document      *SearchDocument        `protobuf:"bytes,2,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProductRequest) Reset() {
	*x = UpsertProductRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProductRequest) ProtoMessage() {}

func (x *UpsertProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProductRequest.ProtoReflect.Descriptor instead.
func (*UpsertProductRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertProductRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpsertProductRequest) GetDocument() *SearchDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

type SearchDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategorySlug  string                 `protobuf:"bytes,4,opt,name=category_slug,json=categorySlug,proto3" json:"category_slug,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDocument) Reset() {
	*x = SearchDocument{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocument) ProtoMessage() {}

func (x *SearchDocument) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocument.ProtoReflect.Descriptor instead.
func (*SearchDocument) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchDocument) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SearchDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchDocument) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchDocument) GetCategorySlug() string {
	if x != nil {
		return x.CategorySlug
	}
	return ""
}

func (x *SearchDocument) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpsertProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProductResponse) Reset() {
	*x = UpsertProductResponse{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProductResponse) ProtoMessage() {}

func (x *UpsertProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProductResponse.ProtoReflect.Descriptor instead.
func (*UpsertProductResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertProductResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

type PruneProductsRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	KeepProductIds          []string               `protobuf:"bytes,1,rep,name=keep_product_ids,json=keepProductIds,proto3" json:"keep_product_ids,omitempty"`
	SourceSnapshotStartedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=source_snapshot_started_at,json=sourceSnapshotStartedAt,proto3" json:"source_snapshot_started_at,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PruneProductsRequest) Reset() {
	*x = PruneProductsRequest{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneProductsRequest) ProtoMessage() {}

func (x *PruneProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneProductsRequest.ProtoReflect.Descriptor instead.
func (*PruneProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *PruneProductsRequest) GetKeepProductIds() []string {
	if x != nil {
		return x.KeepProductIds
	}
	return nil
}

func (x *PruneProductsRequest) GetSourceSnapshotStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SourceSnapshotStartedAt
	}
	return nil
}

type PruneProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       uint64                 `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PruneProductsResponse) Reset() {
	*x = PruneProductsResponse{}
	mi := &file_api_proto_search_v1_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PruneProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PruneProductsResponse) ProtoMessage() {}

func (x *PruneProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_search_v1_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PruneProductsResponse.ProtoReflect.Descriptor instead.
func (*PruneProductsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_search_v1_search_proto_rawDescGZIP(), []int{6}
}

func (x *PruneProductsResponse) GetDeleted() uint64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_api_proto_search_v1_search_proto protoreflect.FileDescriptor

const file_api_proto_search_v1_search_proto_rawDesc = "" +
	"\n" +
	" api/proto/search/v1/search.proto\x12\x12cartlabs.search.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"W\n" +
	"\x16SearchProductsResponse\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\"q\n" +
	"\x14UpsertProductRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12>\n" +
	"\bdocument\x18\x02 \x01(\v2\".cartlabs.search.v1.SearchDocumentR\bdocument\"\xc5\x01\n" +
	"\x0eSearchDocument\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\rcategory_slug\x18\x04 \x01(\tR\fcategorySlug\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"1\n" +
	"\x15UpsertProductResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\"\x99\x01\n" +
	"\x14PruneProductsRequest\x12(\n" +
	"\x10keep_product_ids\x18\x01 \x03(\tR\x0ekeepProductIds\x12W\n" +
	"\x1asource_snapshot_started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x17sourceSnapshotStartedAt\"1\n" +
	"\x15PruneProductsResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x04R\adeleted2\xc4\x02\n" +
	"\rSearchService\x12g\n" +
	"\x0eSearchProducts\x12).cartlabs.search.v1.SearchProductsRequest\x1a*.cartlabs.search.v1.SearchProductsResponse\x12d\n" +
	"\rUpsertProduct\x12(.cartlabs.search.v1.UpsertProductRequest\x1a).cartlabs.search.v1.UpsertProductResponse\x12d\n" +
	"\rPruneProducts\x12(.cartlabs.search.v1.PruneProductsRequest\x1a).cartlabs.search.v1.PruneProductsResponseB:Z8github.com/christolx/cartlabs/internal/contract/searchv1b\x06proto3"

var (
	file_api_proto_search_v1_search_proto_rawDescOnce sync.Once
	file_api_proto_search_v1_search_proto_rawDescData []byte
)

func file_api_proto_search_v1_search_proto_rawDescGZIP() []byte {
	file_api_proto_search_v1_search_proto_rawDescOnce.Do(func() {
		file_api_proto_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)))
	})
	return file_api_proto_search_v1_search_proto_rawDescData
}

var file_api_proto_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_search_v1_search_proto_goTypes = []any{
	(*SearchProductsRequest)(nil),  // 0: cartlabs.search.v1.SearchProductsRequest
	(*SearchProductsResponse)(nil), // 1: cartlabs.search.v1.SearchProductsResponse
	(*UpsertProductRequest)(nil),   // 2: cartlabs.search.v1.UpsertProductRequest
	(*SearchDocument)(nil),         // 3: cartlabs.search.v1.SearchDocument
	(*UpsertProductResponse)(nil),  // 4: cartlabs.search.v1.UpsertProductResponse
	(*PruneProductsRequest)(nil),   // 5: cartlabs.search.v1.PruneProductsRequest
	(*PruneProductsResponse)(nil),  // 6: cartlabs.search.v1.PruneProductsResponse
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_api_proto_search_v1_search_proto_depIdxs = []int32{
	3, // 0: cartlabs.search.v1.UpsertProductRequest.document:type_name -> cartlabs.search.v1.SearchDocument
	7, // 1: cartlabs.search.v1.SearchDocument.updated_at:type_name -> google.protobuf.Timestamp
	7, // 2: cartlabs.search.v1.PruneProductsRequest.source_snapshot_started_at:type_name -> google.protobuf.Timestamp
	0, // 3: cartlabs.search.v1.SearchService.SearchProducts:input_type -> cartlabs.search.v1.SearchProductsRequest
	2, // 4: cartlabs.search.v1.SearchService.UpsertProduct:input_type -> cartlabs.search.v1.UpsertProductRequest
	5, // 5: cartlabs.search.v1.SearchService.PruneProducts:input_type -> cartlabs.search.v1.PruneProductsRequest
	1, // 6: cartlabs.search.v1.SearchService.SearchProducts:output_type -> cartlabs.search.v1.SearchProductsResponse
	4, // 7: cartlabs.search.v1.SearchService.UpsertProduct:output_type -> cartlabs.search.v1.UpsertProductResponse
	6, // 8: cartlabs.search.v1.SearchService.PruneProducts:output_type -> cartlabs.search.v1.PruneProductsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_search_v1_search_proto_init() }
func file_api_proto_search_v1_search_proto_init() {
	if File_api_proto_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_search_v1_search_proto_rawDesc), len(file_api_proto_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_search_v1_search_proto_goTypes,
		DependencyIndexes: file_api_proto_search_v1_search_proto_depIdxs,
		MessageInfos:      file_api_proto_search_v1_search_proto_msgTypes,
	}.Build()
	File_api_proto_search_v1_search_proto = out.File
	file_api_proto_search_v1_search_proto_goTypes = nil
	file_api_proto_search_v1_search_proto_depIdxs = nil
}
