---
k3s_version: v1.36.3+k3s1
cloudflared_enabled: false
cloudflared_tunnel_token: "{{ lookup('ansible.builtin.env', 'CLOUDFLARE_TUNNEL_TOKEN') }}"
github_runner_enabled: false
github_runner_repository_url: https://github.com/christolx/cartlabs
